<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 3 Pruebas de hipótesis paramétricas y no paramétricas | Análisis Estadístico del Dataset de Seguros</title>
  <meta name="description" content="Análisis exploratorio de datos y pruebas de hipótesis paramétricas y no paramétricas aplicadas a un conjunto de datos de pólizas de seguros." />
  <meta name="generator" content="bookdown 0.48 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 3 Pruebas de hipótesis paramétricas y no paramétricas | Análisis Estadístico del Dataset de Seguros" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Análisis exploratorio de datos y pruebas de hipótesis paramétricas y no paramétricas aplicadas a un conjunto de datos de pólizas de seguros." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 3 Pruebas de hipótesis paramétricas y no paramétricas | Análisis Estadístico del Dataset de Seguros" />
  
  <meta name="twitter:description" content="Análisis exploratorio de datos y pruebas de hipótesis paramétricas y no paramétricas aplicadas a un conjunto de datos de pólizas de seguros." />
  

<meta name="author" content="Fernando Cabrera Marriaga y Keisy Polo Peralta" />


<meta name="date" content="2026-09-17" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="intro.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Análisis Estadístico del Dataset de Seguros</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="01-intro.html"><a href="#introducci%C3%B3n"><i class="fa fa-check"></i><b>1</b> Introducción</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1.1</b> Objetivo</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Análisis Exploratorio de Datos (EDA)</a>
<ul>
<li class="chapter" data-level="2.1" data-path="01-intro.html"><a href="#revisi%C3%B3n-de-datos-faltantes-en-las-variables-num%C3%A9ricas"><i class="fa fa-check"></i><b>2.1</b> Revisión de datos faltantes en las variables numéricas</a></li>
<li class="chapter" data-level="2.2" data-path="01-intro.html"><a href="#revisi%C3%B3n-de-datos-faltantes-en-variables-categ%C3%B3ricas"><i class="fa fa-check"></i><b>2.2</b> Revisión de datos faltantes en variables categóricas</a></li>
<li class="chapter" data-level="2.3" data-path="01-intro.html"><a href="#ingenier%C3%ADa-de-caracter%C3%ADsticas-en-variables-categ%C3%B3ricas"><i class="fa fa-check"></i><b>2.3</b> Ingeniería de características en variables categóricas</a></li>
<li class="chapter" data-level="2.4" data-path="01-intro.html"><a href="#an%C3%A1lisis-variable-respuesta-premium-amount"><i class="fa fa-check"></i><b>2.4</b> Análisis variable respuesta (Premium Amount)</a></li>
<li class="chapter" data-level="2.5" data-path="01-intro.html"><a href="#an%C3%A1lisis-de-las-variables-independientes-caracter%C3%ADsticas"><i class="fa fa-check"></i><b>2.5</b> Análisis de las variables independientes (características)</a></li>
<li class="chapter" data-level="2.6" data-path="01-intro.html"><a href="#an%C3%A1lisis-bivariado-variable-caracter%C3%ADstica-vs-variable-respuesta"><i class="fa fa-check"></i><b>2.6</b> Análisis bivariado (Variable característica vs Variable respuesta)</a></li>
<li class="chapter" data-level="2.7" data-path="01-intro.html"><a href="#an%C3%A1lisis-bivariado-independienets-vs-independientes"><i class="fa fa-check"></i><b>2.7</b> Análisis bivariado independienets vs independientes</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="01-intro.html"><a href="#pruebas-de-hip%C3%B3tesis-param%C3%A9tricas-y-no-param%C3%A9tricas"><i class="fa fa-check"></i><b>3</b> Pruebas de hipótesis paramétricas y no paramétricas</a>
<ul>
<li class="chapter" data-level="3.1" data-path="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html"><i class="fa fa-check"></i><b>3.1</b> Conclusiones</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/2939913901/01-intro" target="_blank">Ver repositorio en GitHub</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Análisis Estadístico del Dataset de Seguros</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="pruebas-de-hipótesis-paramétricas-y-no-paramétricas" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Capítulo 3</span> Pruebas de hipótesis paramétricas y no paramétricas<a href="#pruebas-de-hip%C3%B3tesis-param%C3%A9tricas-y-no-param%C3%A9tricas" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Una vez finalizado el análisis exploratorio de los datos, se procede a plantear y resolver un conjunto de preguntas mediante pruebas de hipótesis, con el fin de confirmar de manera estadística algunos de los patrones observados previamente. El objetivo principal de esta sección es evaluar la relación entre las distintas variables del dataset y Premium Amount, verificando si las diferencias o asociaciones detectadas visualmente en el EDA son también estadísticamente significativas. Dado que en el EDA se evidenció que varias variables no presentan un comportamiento normal, se evaluará en cada caso si corresponde aplicar una prueba paramétrica o no paramétrica, según se cumplan o no los supuestos requeridos.</p>
<p>Pregunta 1: ¿Existe una diferencia significativa en el Premium Amount promedio entre clientes fumadores y no fumadores?</p>
<p>Sea μ₁ el promedio de Premium Amount para los clientes no fumadores, y μ₂ el promedio de Premium Amount para los clientes fumadores. Se plantea la siguiente hipótesis:</p>
<p>H₀: μ₁ = μ₂ (no hay diferencia entre los grupos)
H₁: μ₁ ≠ μ₂ (existe una diferencia entre los grupos)</p>
<p>Para dar inicio al análisis, se separan los valores de Premium Amount en dos grupos según la variable Smoking Status, con el fin de trabajar con cada uno de forma independiente en las pruebas posteriores.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb136-1" tabindex="-1"></a>no_fumadores <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Smoking_Status <span class="sc">==</span> <span class="st">&quot;No&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span>
<span id="cb136-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb136-2" tabindex="-1"></a>fumadores <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Smoking_Status <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span></code></pre></div>
<p>Antes de decidir qué tipo de prueba aplicar para comparar los dos grupos, es necesario verificar si la variable Premium Amount cumple con el supuesto de normalidad. Dado el gran tamaño de la muestra, se emplea inicialmente la prueba de Lilliefors, ya que no presenta restricciones en cuanto al número de observaciones y permite empates.</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb137-1" tabindex="-1"></a><span class="fu">library</span>(nortest)</span>
<span id="cb137-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb137-2" tabindex="-1"></a><span class="fu">lillie.test</span>(no_fumadores)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  no_fumadores
## D = 0.11591, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb139-1" tabindex="-1"></a><span class="fu">lillie.test</span>(fumadores)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  fumadores
## D = 0.11656, p-value &lt; 2.2e-16</code></pre>
<p>Con una confianza del 95%, la prueba de Lilliefors muestra que las distribuciones del Premium Amount para los clientes no fumadores (D = 0.11591, p-valor &lt; 0.001) y fumadores (D = 0.11656, p-valor &lt; 0.001) no provienen de una distribución normal, ya que en ambos casos el p-valor es considerablemente menor al nivel de significancia establecido.</p>
<p>Como complemento a la prueba anterior, se aplica también la prueba de Shapiro-Wilk sobre una muestra aleatoria de 5,000 observaciones por grupo, debido a que esta prueba tiene un límite máximo de observaciones permitidas.</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb141-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb141-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb141-2" tabindex="-1"></a>muestra_no <span class="ot">&lt;-</span> <span class="fu">sample</span>(no_fumadores, <span class="dv">5000</span>)</span>
<span id="cb141-3"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb141-3" tabindex="-1"></a>muestra_yes <span class="ot">&lt;-</span> <span class="fu">sample</span>(fumadores, <span class="dv">5000</span>)</span>
<span id="cb141-4"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb141-4" tabindex="-1"></a></span>
<span id="cb141-5"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb141-5" tabindex="-1"></a><span class="fu">shapiro.test</span>(muestra_no)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  muestra_no
## W = 0.89415, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb143-1" tabindex="-1"></a><span class="fu">shapiro.test</span>(muestra_yes)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  muestra_yes
## W = 0.90441, p-value &lt; 2.2e-16</code></pre>
<p>Los resultados confirman lo obtenido con Lilliefors: los clientes no fumadores (W = 0.89415, p-valor &lt; 0.001) y fumadores (W = 0.90441, p-valor &lt; 0.001) tampoco muestran un comportamiento normal en la muestra evaluada.</p>
<p>Dado que no se cumple el supuesto de normalidad en ninguno de los dos grupos, no es adecuado aplicar una prueba paramétrica (t-test) para comparar medias. En su lugar, se opta por una prueba no paramétrica que compara la tendencia central de las distribuciones. Se replantea entonces la hipótesis en términos de mediana (η), coherente con lo que efectivamente evalúa la prueba de Mann-Whitney-Wilcoxon:</p>
<p>Sea η₁ la mediana de Premium Amount para los clientes no fumadores, y η₂ la mediana para los clientes fumadores:</p>
<p>H₀: η₁ = η₂
H₁: η₁ ≠ η₂</p>
<p>Antes de aplicar la prueba de Mann-Whitney-Wilcoxon, se verifica la homogeneidad de varianzas entre los grupos mediante la prueba de Levene.</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb145-1" tabindex="-1"></a><span class="fu">leveneTest</span>(Premium_Amount <span class="sc">~</span> Smoking_Status, <span class="at">data =</span> df, <span class="at">center =</span> <span class="st">&quot;median&quot;</span>)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = &quot;median&quot;)
##            Df F value Pr(&gt;F)
## group       1  0.7404 0.3895
##       1199998</code></pre>
<p>Con una confianza del 95%, la prueba de Levene indica que no se encuentran diferencias estadísticamente significativas en la varianza del Premium Amount entre los clientes fumadores y no fumadores (F(1) = 0.7404, p-valor = 0.3895).</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb147-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb147-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb147-2" tabindex="-1"></a>  rstatix<span class="sc">::</span><span class="fu">wilcox_test</span>(Premium_Amount <span class="sc">~</span> Smoking_Status, <span class="at">paired =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 7
##   .y.            group1 group2     n1     n2    statistic     p
## * &lt;chr&gt;          &lt;chr&gt;  &lt;chr&gt;   &lt;int&gt;  &lt;int&gt;        &lt;dbl&gt; &lt;dbl&gt;
## 1 Premium_Amount No     Yes    598127 601873 179920076580 0.680</code></pre>
<p>Con una confianza del 95%, la prueba de Mann-Whitney-Wilcoxon indica que no hay evidencia estadísticamente significativa de una diferencia en la mediana del Premium Amount entre clientes fumadores y no fumadores (U = 179920076580, p-valor = 0.6803), por lo que no se rechaza H₀.</p>
<p>A pesar de no encontrar una diferencia estadísticamente significativa, se calcula el tamaño del efecto para complementar el análisis.</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb149-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb149-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb149-2" tabindex="-1"></a>  <span class="fu">wilcox_effsize</span>(Premium_Amount <span class="sc">~</span> Smoking_Status, <span class="at">paired =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 7
##   .y.            group1 group2  effsize     n1     n2 magnitude
## * &lt;chr&gt;          &lt;chr&gt;  &lt;chr&gt;     &lt;dbl&gt;  &lt;int&gt;  &lt;int&gt; &lt;ord&gt;    
## 1 Premium_Amount No     Yes    0.000376 598127 601873 small</code></pre>
<p>Con base en el resultado del tamaño del efecto (r = 0.000376), se observa un efecto prácticamente nulo entre los grupos de fumadores y no fumadores. Aunque la magnitud se clasifica como “small” (pequeña) según la escala utilizada, el valor es tan cercano a cero que confirma que, más allá de la falta de significancia estadística ya encontrada, la diferencia entre ambos grupos tampoco tiene ninguna relevancia práctica.</p>
<p>Pregunta 2: ¿Existen diferencias significativas en el Premium Amount promedio entre los tres tipos de póliza (Basic, Comprehensive, Premium)?</p>
<p>H₀: las tres poblaciones (Basic, Comprehensive, Premium) provienen de la misma distribución.
H₁: al menos una población proviene de una distribución distinta.</p>
<p>Antes de decidir qué tipo de prueba aplicar para comparar los tres tipos de póliza, es necesario verificar si la variable Premium Amount cumple con el supuesto de normalidad en cada uno de los tres grupos. Para ello, se utiliza la prueba de Lilliefors.</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb151-1" tabindex="-1"></a>basic <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Policy_Type <span class="sc">==</span> <span class="st">&quot;Basic&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span>
<span id="cb151-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb151-2" tabindex="-1"></a>comprehensive <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Policy_Type <span class="sc">==</span> <span class="st">&quot;Comprehensive&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span>
<span id="cb151-3"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb151-3" tabindex="-1"></a>premium <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Policy_Type <span class="sc">==</span> <span class="st">&quot;Premium&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span>
<span id="cb151-4"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb151-4" tabindex="-1"></a></span>
<span id="cb151-5"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb151-5" tabindex="-1"></a><span class="fu">lillie.test</span>(basic)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  basic
## D = 0.11591, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb153-1" tabindex="-1"></a><span class="fu">lillie.test</span>(comprehensive)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  comprehensive
## D = 0.11593, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb155-1" tabindex="-1"></a><span class="fu">lillie.test</span>(premium)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  premium
## D = 0.11687, p-value &lt; 2.2e-16</code></pre>
<p>Con una confianza del 95%, la prueba de Lilliefors muestra que las distribuciones del Premium Amount para los tipos de póliza Basic (D = 0.11591, p-valor &lt; 0.001), Comprehensive (D = 0.11593, p-valor &lt; 0.001) y Premium (D = 0.11687, p-valor &lt; 0.001) no provienen de una distribución normal, ya que en los tres casos el p-valor es considerablemente menor al nivel de significancia establecido.</p>
<p>Antes de aplicar la prueba de Kruskal-Wallis, se verifica la homogeneidad de varianzas entre los tres grupos mediante la prueba de Levene.</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb157-1" tabindex="-1"></a><span class="fu">leveneTest</span>(Premium_Amount <span class="sc">~</span> Policy_Type, <span class="at">data =</span> df, <span class="at">center =</span> <span class="st">&quot;median&quot;</span>)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = &quot;median&quot;)
##            Df F value Pr(&gt;F)
## group       2  0.0703 0.9321
##       1199997</code></pre>
<p>Con una confianza del 95%, la prueba de Levene indica que no se encuentran diferencias estadísticamente significativas en la varianza del Premium Amount entre los tres tipos de póliza (F(2) = 0.0703, p-valor = 0.9321).</p>
<p>Una vez verificados los supuestos, se procede a aplicar la prueba de Kruskal-Wallis para determinar si existen diferencias significativas en el Premium Amount entre los tres tipos de póliza.</p>
<div class="sourceCode" id="cb159"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb159-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb159-1" tabindex="-1"></a><span class="fu">kruskal.test</span>(Premium_Amount <span class="sc">~</span> Policy_Type, <span class="at">data =</span> df)</span></code></pre></div>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  Premium_Amount by Policy_Type
## Kruskal-Wallis chi-squared = 1.9075, df = 2, p-value = 0.3853</code></pre>
<p>Con una confianza del 95%, la prueba de Kruskal-Wallis indica que no existen diferencias estadísticamente significativas en el Premium Amount entre los tres tipos de póliza (χ²(2) = 1.9075, p-valor = 0.3853).</p>
<p>A pesar de no encontrar una diferencia estadísticamente significativa, se calcula el tamaño del efecto para complementar el análisis.</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb161-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb161-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb161-2" tabindex="-1"></a>  <span class="fu">kruskal_effsize</span>(Premium_Amount <span class="sc">~</span> Policy_Type)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 5
##   .y.                  n effsize method  magnitude
## * &lt;chr&gt;            &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;   &lt;ord&gt;    
## 1 Premium_Amount 1200000       0 eta2[H] small</code></pre>
<p>El tamaño del efecto obtenido (η²[H] = 0) confirma que no hay ningún efecto entre los tipos de póliza sobre el Premium Amount. Esto va en línea con el resultado de Kruskal-Wallis: ni hay diferencia significativa, ni tampoco relevancia práctica entre los grupos Basic, Comprehensive y Premium.</p>
<p>Pregunta 3: ¿Existe una correlación significativa entre Health Score y Premium Amount?</p>
<p>Sea ρ el coeficiente de correlación poblacional entre Health Score y Premium Amount.</p>
<p>H₀: ρ = 0 (no existe correlación entre las variables)
H₁: ρ ≠ 0 (existe correlación entre las variables)</p>
<p>Antes de decidir qué coeficiente de correlación utilizar (Pearson o Spearman), es necesario verificar si ambas variables cumplen el supuesto de normalidad. Para ello, se aplica la prueba de Lilliefors sobre cada una.</p>
<div class="sourceCode" id="cb163"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb163-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb163-1" tabindex="-1"></a><span class="fu">lillie.test</span>(df<span class="sc">$</span>Health_Score)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  df$Health_Score
## D = 0.064144, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb165-1" tabindex="-1"></a><span class="fu">lillie.test</span>(df<span class="sc">$</span>Premium_Amount)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  df$Premium_Amount
## D = 0.11624, p-value &lt; 2.2e-16</code></pre>
<p>Con una confianza del 95%, la prueba de Lilliefors muestra que ni Health Score (D = 0.047379, p-valor &lt; 0.001) ni Premium Amount (D = 0.11624, p-valor &lt; 0.001) provienen de una distribución normal, ya que en ambos casos el p-valor es considerablemente menor al nivel de significancia establecido.</p>
<p>Dado que ninguna de las dos variables cumple el supuesto de normalidad, se utiliza el coeficiente de correlación de Spearman para evaluar la relación entre Health Score y Premium Amount.</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb167-1" tabindex="-1"></a><span class="fu">cor.test</span>(df<span class="sc">$</span>Health_Score, df<span class="sc">$</span>Premium_Amount, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>)</span></code></pre></div>
<pre><code>## Warning in cor.test.default(df$Health_Score, df$Premium_Amount, method =
## &quot;spearman&quot;): Cannot compute exact p-value with ties</code></pre>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  df$Health_Score and df$Premium_Amount
## S = 2.8358e+17, p-value &lt; 2.2e-16
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##        rho 
## 0.01535738</code></pre>
<p>Con una confianza del 95%, la prueba de correlación de Spearman indica que existe una correlación estadísticamente significativa entre Health Score y Premium Amount (S = 2.3408e+17, p-valor &lt; 0.001, rho = 0.01601). Sin embargo, el valor del coeficiente de correlación (ρ = 0.016) es extremadamente bajo, lo que indica que, a pesar de ser significativa desde el punto de vista estadístico, la relación entre ambas variables es prácticamente nula en términos prácticos.</p>
<p>Pregunta 4: ¿Existe relación entre Smoking Status y Policy Type?</p>
<p>H₀: Smoking Status y Policy Type son independientes (no hay relación entre ellas).
H₁: Smoking Status y Policy Type no son independientes (existe relación entre ellas).</p>
<p>Para evaluar si existe relación entre Smoking Status y Policy Type, se construye primero una tabla de contingencia que muestra la frecuencia de cada combinación posible entre ambas variables.</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb170-1" tabindex="-1"></a>tabla <span class="ot">&lt;-</span> <span class="fu">table</span>(df<span class="sc">$</span>Smoking_Status, df<span class="sc">$</span>Policy_Type)</span>
<span id="cb170-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb170-2" tabindex="-1"></a>tabla</span></code></pre></div>
<pre><code>##      
##        Basic Comprehensive Premium
##   No  198061        199509  200557
##   Yes 200493        200091  201289</code></pre>
<p>La tabla de contingencia muestra la distribución de frecuencias entre Smoking Status y Policy Type. Se observa que las frecuencias son bastante similares entre las combinaciones, oscilando entre 198,061 y 201,289 clientes en cada celda, sin que se note a simple vista una concentración marcada en alguna combinación en particular.</p>
<p>Antes de aplicar la prueba de Chi-cuadrado, es necesario verificar que los valores esperados en cada celda sean mayores o iguales a 5, ya que este es un supuesto fundamental para la validez de la prueba.</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb172-1" tabindex="-1"></a><span class="fu">chisq.test</span>(tabla)<span class="sc">$</span>expected</span></code></pre></div>
<pre><code>##      
##          Basic Comprehensive  Premium
##   No  198654.9      199176.3 200295.8
##   Yes 199899.1      200423.7 201550.2</code></pre>
<p>Se verifica que todos los valores esperados en la tabla de contingencia son considerablemente mayores a 5 (el valor más bajo es 198,654.9), por lo que se cumple el supuesto necesario para aplicar la prueba de Chi-cuadrado con validez.</p>
<p>Aplicamos la prueba chi-cuadrado</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb174-1" tabindex="-1"></a><span class="fu">chisq.test</span>(tabla)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  tabla
## X-squared = 5.3276, df = 2, p-value = 0.06968</code></pre>
<p>Con una confianza del 95%, la prueba de Chi-cuadrado de Pearson indica que no existe evidencia estadísticamente significativa de una relación entre Smoking Status y Policy Type (χ²(2) = 5.3276, p-valor = 0.06968), ya que el p-valor es mayor al nivel de significancia establecido.</p>
<p>Pregunta 5: ¿Existe una diferencia significativa en el Premium Amount promedio entre clientes hombres y mujeres?</p>
<p>Inicialmente, se busca comparar el promedio de Premium Amount entre ambos grupos. Sea μ₁ el promedio de Premium Amount para clientes Female, y μ₂ el promedio para clientes Male:</p>
<p>H₀: μ₁ = μ₂
H₁: μ₁ ≠ μ₂</p>
<p>Antes de decidir qué tipo de prueba aplicar, es necesario verificar si la variable Premium Amount cumple con el supuesto de normalidad en cada grupo. Para ello, se separan los valores de Premium Amount según Gender y se aplica la prueba de Lilliefors.</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb176-1" tabindex="-1"></a>female <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Gender <span class="sc">==</span> <span class="st">&quot;Female&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span>
<span id="cb176-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb176-2" tabindex="-1"></a>male <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Gender <span class="sc">==</span> <span class="st">&quot;Male&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span>
<span id="cb176-3"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb176-3" tabindex="-1"></a></span>
<span id="cb176-4"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb176-4" tabindex="-1"></a><span class="fu">lillie.test</span>(female)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  female
## D = 0.11638, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb178-1" tabindex="-1"></a><span class="fu">lillie.test</span>(male)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  male
## D = 0.1161, p-value &lt; 2.2e-16</code></pre>
<p>Con una confianza del 95%, la prueba de Lilliefors muestra que las distribuciones del Premium Amount para clientes Female y Male no provienen de una distribución normal, ya que en ambos casos el p-valor es considerablemente menor al nivel de significancia establecido.</p>
<p>Como complemento, se aplica también la prueba de Shapiro-Wilk sobre una muestra aleatoria de 5,000 observaciones por grupo:</p>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb180-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb180-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb180-2" tabindex="-1"></a>muestra_female <span class="ot">&lt;-</span> <span class="fu">sample</span>(female, <span class="dv">5000</span>)</span>
<span id="cb180-3"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb180-3" tabindex="-1"></a>muestra_male <span class="ot">&lt;-</span> <span class="fu">sample</span>(male, <span class="dv">5000</span>)</span>
<span id="cb180-4"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb180-4" tabindex="-1"></a></span>
<span id="cb180-5"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb180-5" tabindex="-1"></a><span class="fu">shapiro.test</span>(muestra_female)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  muestra_female
## W = 0.89798, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb182-1" tabindex="-1"></a><span class="fu">shapiro.test</span>(muestra_male)</span></code></pre></div>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  muestra_male
## W = 0.90381, p-value &lt; 2.2e-16</code></pre>
<p>Los resultados confirman lo obtenido con Lilliefors: ni Female ni Male muestran un comportamiento normal en la muestra evaluada.</p>
<p>Dado que no se cumple el supuesto de normalidad en ninguno de los dos grupos, no es adecuado aplicar una prueba paramétrica (t-test). Se replantea entonces la hipótesis en términos de mediana (η), coherente con lo que evalúa Mann-Whitney-Wilcoxon:</p>
<p>Sea η₁ la mediana de Premium Amount para clientes Female, y η₂ la mediana para clientes Male:</p>
<p>H₀: η₁ = η₂
H₁: η₁ ≠ η₂</p>
<p>Antes de aplicar Mann-Whitney-Wilcoxon, se verifica la homogeneidad de varianzas mediante Levene:</p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb184-1" tabindex="-1"></a><span class="fu">leveneTest</span>(Premium_Amount <span class="sc">~</span> Gender, <span class="at">data =</span> df, <span class="at">center =</span> <span class="st">&quot;median&quot;</span>)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = &quot;median&quot;)
##            Df F value Pr(&gt;F)
## group       1  1.2907 0.2559
##       1199998</code></pre>
<p>Con una confianza del 95%, la prueba de Levene indica que no se encuentran diferencias estadísticamente significativas en la varianza del Premium Amount entre clientes Female y Male (F(1) = 1.2907, p-valor = 0.2559), ya que el p-valor es mayor al nivel de significancia establecido (0.05). Esto significa que se cumple el supuesto de homogeneidad de varianzas, por lo que se puede continuar con la prueba de Mann-Whitney-Wilcoxon sin inconvenientes.</p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb186-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb186-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb186-2" tabindex="-1"></a>  rstatix<span class="sc">::</span><span class="fu">wilcox_test</span>(Premium_Amount <span class="sc">~</span> Gender, <span class="at">paired =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 7
##   .y.            group1 group2     n1     n2    statistic     p
## * &lt;chr&gt;          &lt;chr&gt;  &lt;chr&gt;   &lt;int&gt;  &lt;int&gt;        &lt;dbl&gt; &lt;dbl&gt;
## 1 Premium_Amount Female Male   597429 602571 179971290482 0.893</code></pre>
<p>Con una confianza del 95%, la prueba de Mann-Whitney-Wilcoxon indica que no hay evidencia estadísticamente significativa de una diferencia en la mediana del Premium Amount entre clientes Female y Male (U = 179,971,290,482, p-valor = 0.8935), ya que el p-valor es considerablemente mayor al nivel de significancia establecido (0.05). Por lo tanto, no se rechaza H₀.</p>
<p>Y finalmente el tamaño del efecto:</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb188-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb188-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb188-2" tabindex="-1"></a>  rstatix<span class="sc">::</span><span class="fu">wilcox_effsize</span>(Premium_Amount <span class="sc">~</span> Gender, <span class="at">paired =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 7
##   .y.            group1 group2  effsize     n1     n2 magnitude
## * &lt;chr&gt;          &lt;chr&gt;  &lt;chr&gt;     &lt;dbl&gt;  &lt;int&gt;  &lt;int&gt; &lt;ord&gt;    
## 1 Premium_Amount Female Male   0.000122 597429 602571 small</code></pre>
<p>Con base en el tamaño del efecto obtenido (r = 0.000122), se observa un efecto prácticamente nulo entre los grupos Female y Male. Aunque la magnitud se clasifica como “small” (pequeña) según la escala utilizada (es la etiqueta más baja disponible, no implica que el efecto sea moderado), el valor es tan cercano a cero que confirma que, más allá de la falta de significancia estadística ya encontrada, la diferencia entre ambos géneros tampoco tiene ninguna relevancia práctica.</p>
<p>Con una confianza del 95%, la prueba de Mann-Whitney-Wilcoxon indica que no hay evidencia estadísticamente significativa de una diferencia en la mediana del Premium Amount entre clientes Female y Male (U = 179,971,290,482, p-valor = 0.8935), por lo que no se rechaza H₀. Adicionalmente, el tamaño del efecto obtenido (r = 0.000122) confirma un efecto prácticamente nulo entre ambos grupos, lo que indica que, más allá de la falta de significancia estadística, la diferencia entre géneros tampoco tiene ninguna relevancia práctica.</p>
<p>Pregunta 6: ¿Existen diferencias significativas en el Premium Amount promedio entre las cuatro frecuencias de ejercicio (Rarely, Monthly, Weekly, Daily)?</p>
<p>H₀: las cuatro poblaciones (Rarely, Monthly, Weekly, Daily) provienen de la misma distribución.
H₁: al menos una población proviene de una distribución distinta.</p>
<p>Antes de decidir qué tipo de prueba aplicar para comparar los cuatro grupos, es necesario verificar si la variable Premium Amount cumple con el supuesto de normalidad en cada uno de ellos. Para ello, se utiliza la prueba de Lilliefors.</p>
<div class="sourceCode" id="cb190"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb190-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb190-1" tabindex="-1"></a>rarely <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Exercise_Frequency <span class="sc">==</span> <span class="st">&quot;Rarely&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span>
<span id="cb190-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb190-2" tabindex="-1"></a>monthly <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Exercise_Frequency <span class="sc">==</span> <span class="st">&quot;Monthly&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span>
<span id="cb190-3"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb190-3" tabindex="-1"></a>weekly <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Exercise_Frequency <span class="sc">==</span> <span class="st">&quot;Weekly&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span>
<span id="cb190-4"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb190-4" tabindex="-1"></a>daily <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Exercise_Frequency <span class="sc">==</span> <span class="st">&quot;Daily&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span>
<span id="cb190-5"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb190-5" tabindex="-1"></a></span>
<span id="cb190-6"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb190-6" tabindex="-1"></a><span class="fu">lillie.test</span>(rarely)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  rarely
## D = 0.11657, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb192"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb192-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb192-1" tabindex="-1"></a><span class="fu">lillie.test</span>(monthly)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  monthly
## D = 0.1169, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb194"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb194-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb194-1" tabindex="-1"></a><span class="fu">lillie.test</span>(weekly)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  weekly
## D = 0.11577, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb196"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb196-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb196-1" tabindex="-1"></a><span class="fu">lillie.test</span>(daily)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  daily
## D = 0.11574, p-value &lt; 2.2e-16</code></pre>
<p>Con una confianza del 95%, la prueba de Lilliefors muestra que las distribuciones del Premium Amount para las cuatro frecuencias de ejercicio (Rarely, Monthly, Weekly, Daily) no provienen de una distribución normal, ya que en los cuatro casos el p-valor es considerablemente menor al nivel de significancia establecido.</p>
<p>Antes de aplicar la prueba de Kruskal-Wallis, se verifica la homogeneidad de varianzas entre los cuatro grupos mediante la prueba de Levene</p>
<div class="sourceCode" id="cb198"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb198-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb198-1" tabindex="-1"></a><span class="fu">leveneTest</span>(Premium_Amount <span class="sc">~</span> Exercise_Frequency, <span class="at">data =</span> df, <span class="at">center =</span> <span class="st">&quot;median&quot;</span>)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = &quot;median&quot;)
##            Df F value Pr(&gt;F)
## group       3  0.8489 0.4669
##       1199996</code></pre>
<p>Con una confianza del 95%, la prueba de Levene indica que no se encuentran diferencias estadísticamente significativas en la varianza del Premium Amount entre las cuatro frecuencias de ejercicio (F(3) = 0.8489, p-valor = 0.4669), ya que el p-valor es mayor al nivel de significancia establecido. Esto confirma que se cumple el supuesto de homogeneidad de varianzas, por lo que se puede continuar con la prueba de Kruskal-Wallis sin inconvenientes.</p>
<div class="sourceCode" id="cb200"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb200-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb200-1" tabindex="-1"></a><span class="fu">kruskal.test</span>(Premium_Amount <span class="sc">~</span> Exercise_Frequency, <span class="at">data =</span> df)</span></code></pre></div>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  Premium_Amount by Exercise_Frequency
## Kruskal-Wallis chi-squared = 2.7564, df = 3, p-value = 0.4307</code></pre>
<p>Con una confianza del 95%, la prueba de Kruskal-Wallis indica que no existen diferencias estadísticamente significativas en el Premium Amount entre las cuatro frecuencias de ejercicio (χ²(3) = 2.7564, p-valor = 0.4307), ya que el p-valor es considerablemente mayor al nivel de significancia establecido. Por lo tanto, no se rechaza H₀.</p>
<p>A pesar de no encontrar una diferencia estadísticamente significativa, se calcula el tamaño del efecto para complementar el análisis.</p>
<div class="sourceCode" id="cb202"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb202-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb202-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb202-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb202-2" tabindex="-1"></a>  rstatix<span class="sc">::</span><span class="fu">kruskal_effsize</span>(Premium_Amount <span class="sc">~</span> Exercise_Frequency)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 5
##   .y.                  n effsize method  magnitude
## * &lt;chr&gt;            &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;   &lt;ord&gt;    
## 1 Premium_Amount 1200000       0 eta2[H] small</code></pre>
<p>El tamaño del efecto obtenido (η²[H] = 0) confirma que no hay ningún efecto entre las frecuencias de ejercicio sobre el Premium Amount. Esto va en línea con el resultado de Kruskal-Wallis: ni hay diferencia significativa, ni tampoco relevancia práctica entre los grupos Rarely, Monthly, Weekly y Daily.</p>
<p>Con una confianza del 95%, tanto la prueba de Kruskal-Wallis (χ²(3) = 2.7564, p-valor = 0.4307) como el tamaño del efecto (η²[H] = 0) indican que no existen diferencias significativas ni relevancia práctica en el Premium Amount entre las cuatro frecuencias de ejercicio, por lo que no se rechaza H₀.</p>
<p>Pregunta 7: ¿Existe una correlación significativa entre Annual Income y Vehicle Age?</p>
<p>Sea ρ el coeficiente de correlación poblacional entre Annual Income y Vehicle Age.</p>
<p>H₀: ρ = 0 (no existe correlación entre las variables)
H₁: ρ ≠ 0 (existe correlación entre las variables)</p>
<p>Antes de decidir qué coeficiente de correlación utilizar (Pearson o Spearman), es necesario verificar si ambas variables cumplen el supuesto de normalidad. Para ello, se aplica la prueba de Lilliefors sobre cada una.</p>
<div class="sourceCode" id="cb204"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb204-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb204-1" tabindex="-1"></a><span class="fu">lillie.test</span>(df<span class="sc">$</span>Annual_Income)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  df$Annual_Income
## D = 0.15271, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb206"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb206-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb206-1" tabindex="-1"></a><span class="fu">lillie.test</span>(df<span class="sc">$</span>Vehicle_Age)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  df$Vehicle_Age
## D = 0.083798, p-value &lt; 2.2e-16</code></pre>
<p>Con una confianza del 95%, la prueba de Lilliefors muestra que ni Annual Income (D = 0.15453, p-valor &lt; 0.001) ni Vehicle Age (D = 0.083797, p-valor &lt; 0.001) provienen de una distribución normal, ya que en ambos casos el p-valor es considerablemente menor al nivel de significancia establecido.</p>
<p>Dado que ninguna de las dos variables cumple el supuesto de normalidad, se utiliza el coeficiente de correlación de Spearman para evaluar la relación entre Annual Income y Vehicle Age.</p>
<div class="sourceCode" id="cb208"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb208-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb208-1" tabindex="-1"></a><span class="fu">cor.test</span>(df<span class="sc">$</span>Annual_Income, df<span class="sc">$</span>Vehicle_Age, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>)</span></code></pre></div>
<pre><code>## Warning in cor.test.default(df$Annual_Income, df$Vehicle_Age, method =
## &quot;spearman&quot;): Cannot compute exact p-value with ties</code></pre>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  df$Annual_Income and df$Vehicle_Age
## S = 2.8811e+17, p-value = 0.6814
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##          rho 
## -0.000374792</code></pre>
<p>Con una confianza del 95%, la prueba de correlación de Spearman indica que no existe una correlación estadísticamente significativa entre Annual Income y Vehicle Age (S = 2.5692e+17, p-valor = 0.7118, ρ = -0.0003), por lo que no se rechaza H₀. El coeficiente de correlación, prácticamente nulo, confirma que no existe relación real entre ambas variables, resolviendo la aparente tensión observada en el EDA entre la matriz de correlación y el scatterplot.</p>
<p>Pregunta 8: ¿Existe relación entre Smoking Status y Exercise Frequency?</p>
<p>H₀: Smoking Status y Exercise Frequency son independientes (no hay relación entre ellas).
H₁: Smoking Status y Exercise Frequency no son independientes (existe relación entre ellas).</p>
<p>Para evaluar si existe relación entre Smoking Status y Exercise Frequency, se construye primero una tabla de contingencia que muestra la frecuencia de cada combinación posible entre ambas variables.</p>
<div class="sourceCode" id="cb211"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb211-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb211-1" tabindex="-1"></a>tabla2 <span class="ot">&lt;-</span> <span class="fu">table</span>(df<span class="sc">$</span>Smoking_Status, df<span class="sc">$</span>Exercise_Frequency)</span>
<span id="cb211-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb211-2" tabindex="-1"></a>tabla2</span></code></pre></div>
<pre><code>##      
##       Rarely Monthly Weekly  Daily
##   No  148910  149477 152513 147227
##   Yes 150510  150353 153666 147344</code></pre>
<p>La tabla de contingencia muestra la distribución de frecuencias entre Smoking Status y Exercise Frequency. Se observa que las frecuencias son bastante similares entre las combinaciones, oscilando entre 147,227 y 153,666 clientes en cada celda, sin que se note a simple vista una concentración marcada en alguna combinación en particular. Tanto fumadores como no fumadores se distribuyen de forma prácticamente pareja entre las cuatro frecuencias de ejercicio.</p>
<p>Antes de aplicar la prueba de Chi-cuadrado, es necesario verificar que los valores esperados en cada celda sean mayores o iguales a 5, ya que este es un supuesto fundamental para la validez de la prueba.</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb213-1" tabindex="-1"></a><span class="fu">chisq.test</span>(tabla2)<span class="sc">$</span>expected</span></code></pre></div>
<pre><code>##      
##         Rarely Monthly   Weekly    Daily
##   No  149242.7  149447 152611.6 146825.7
##   Yes 150177.3  150383 153567.4 147745.3</code></pre>
<p>Se verifica que todos los valores esperados en la tabla de contingencia son considerablemente mayores a 5 (el valor más bajo es 146,825.7), por lo que se cumple el supuesto necesario para aplicar la prueba de Chi-cuadrado con validez.</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb215-1" tabindex="-1"></a><span class="fu">chisq.test</span>(tabla2)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s Chi-squared test
## 
## data:  tabla2
## X-squared = 3.8039, df = 3, p-value = 0.2834</code></pre>
<p>Con una confianza del 95%, la prueba de Chi-cuadrado de Pearson indica que no existe evidencia estadísticamente significativa de una relación entre Smoking Status y Exercise Frequency (χ²(3) = 3.8039, p-valor = 0.2834), por lo que no se rechaza H₀.</p>
<p>Pregunta 9: ¿Existen diferencias significativas en el Premium Amount promedio entre los tres estados civiles (Divorced, Married, Single)?</p>
<p>H₀: las tres poblaciones (Divorced, Married, Single) provienen de la misma distribución.
H₁: al menos una población proviene de una distribución distinta.</p>
<p>Para dar inicio al análisis, se separan los valores de Premium Amount en tres grupos según la variable Marital Status, con el fin de trabajar con cada uno de forma independiente en las pruebas posteriores.</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb217-1" tabindex="-1"></a>divorced <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Marital_Status <span class="sc">==</span> <span class="st">&quot;Divorced&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span>
<span id="cb217-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb217-2" tabindex="-1"></a>married  <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Marital_Status <span class="sc">==</span> <span class="st">&quot;Married&quot;</span>)  <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span>
<span id="cb217-3"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb217-3" tabindex="-1"></a>single   <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Marital_Status <span class="sc">==</span> <span class="st">&quot;Single&quot;</span>)   <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span></code></pre></div>
<p>Antes de decidir qué tipo de prueba aplicar para comparar los tres estados civiles, es necesario verificar si la variable Premium Amount cumple con el supuesto de normalidad en cada grupo. Para ello, se emplea la prueba de Lilliefors, ya que no presenta restricciones en cuanto al número de observaciones y permite empates.</p>
<div class="sourceCode" id="cb218"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb218-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb218-1" tabindex="-1"></a><span class="fu">lillie.test</span>(divorced)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  divorced
## D = 0.11686, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb220"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb220-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb220-1" tabindex="-1"></a><span class="fu">lillie.test</span>(married)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  married
## D = 0.11649, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb222"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb222-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb222-1" tabindex="-1"></a><span class="fu">lillie.test</span>(single)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  single
## D = 0.1154, p-value &lt; 2.2e-16</code></pre>
<p>Con una confianza del 95%, la prueba de Lilliefors muestra que las distribuciones del Premium Amount para los clientes Divorced (D = 0.11686, p-valor &lt; 0.001), Married (D = 0.11649, p-valor &lt; 0.001) y Single (D = 0.11617, p-valor &lt; 0.001) no provienen de una distribución normal, ya que en los tres casos el p-valor es considerablemente menor al nivel de significancia establecido.</p>
<p>Dado que no se cumple el supuesto de normalidad en ninguno de los tres grupos, no es adecuado aplicar una prueba paramétrica (ANOVA) para comparar medias. En su lugar, se opta por una prueba no paramétrica que compara la tendencia central de las distribuciones. Se replantea entonces la hipótesis en términos de mediana (η), coherente con lo que efectivamente evalúa la prueba de Kruskal-Wallis:</p>
<p>Sea η₁, η₂ y η₃ las medianas de Premium Amount para los clientes Divorced, Married y Single, respectivamente:</p>
<p>H₀: η₁ = η₂ = η₃
H₁: al menos una mediana es diferente</p>
<p>Antes de aplicar la prueba de Kruskal-Wallis, se verifica la homogeneidad de varianzas entre los tres grupos mediante la prueba de Levene.</p>
<div class="sourceCode" id="cb224"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb224-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb224-1" tabindex="-1"></a><span class="fu">leveneTest</span>(Premium_Amount <span class="sc">~</span> Marital_Status, <span class="at">data =</span> df, <span class="at">center =</span> <span class="st">&quot;median&quot;</span>)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = &quot;median&quot;)
##            Df F value Pr(&gt;F)
## group       2   2.135 0.1182
##       1199997</code></pre>
<p>Con una confianza del 95%, la prueba de Levene indica que no se encuentran diferencias estadísticamente significativas en la varianza del Premium Amount entre los tres estados civiles (F(2) = 0.8382, p-valor = 0.4325), ya que el p-valor es mayor al nivel de significancia establecido. Esto confirma que se cumple el supuesto de homogeneidad de varianzas, por lo que se puede continuar con la prueba de Kruskal-Wallis sin inconvenientes.</p>
<div class="sourceCode" id="cb226"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb226-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb226-1" tabindex="-1"></a><span class="fu">kruskal.test</span>(Premium_Amount <span class="sc">~</span> Marital_Status, <span class="at">data =</span> df)</span></code></pre></div>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  Premium_Amount by Marital_Status
## Kruskal-Wallis chi-squared = 18.974, df = 2, p-value = 7.582e-05</code></pre>
<p>Con una confianza del 95%, la prueba de Kruskal-Wallis indica que sí existen diferencias estadísticamente significativas en el Premium Amount entre los tres estados civiles (χ²(2) = 18.974, p-valor &lt; 0.001), ya que el p-valor es considerablemente menor al nivel de significancia establecido. Por lo tanto, se rechaza H₀.</p>
<p>Dado que la prueba resultó significativa, se calcula el tamaño del efecto para complementar el análisis.</p>
<div class="sourceCode" id="cb228"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb228-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb228-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb228-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb228-2" tabindex="-1"></a>  <span class="fu">kruskal_effsize</span>(Premium_Amount <span class="sc">~</span> Marital_Status)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 5
##   .y.                  n   effsize method  magnitude
## * &lt;chr&gt;            &lt;int&gt;     &lt;dbl&gt; &lt;chr&gt;   &lt;ord&gt;    
## 1 Premium_Amount 1200000 0.0000141 eta2[H] small</code></pre>
<p>El tamaño del efecto obtenido fue de 0, lo que confirma que no hay ningún efecto entre los estados civiles sobre el Premium Amount. Esto va en línea con el resultado de Kruskal-Wallis: ni hay diferencia significativa, ni tampoco relevancia práctica entre los grupos Divorced, Married y Single.</p>
<p>En conclusión, con una confianza del 95%, tanto la prueba de Kruskal-Wallis (χ²(2) = 1.1676, p-valor = 0.5578) como el tamaño del efecto (valor de 0) indican que no existen diferencias significativas ni relevancia práctica en el Premium Amount entre los tres estados civiles, por lo que no se rechaza H₀.</p>
<p>Pregunta 10: ¿Existen diferencias significativas en el Premium Amount promedio entre los cuatro niveles educativos (High School, Bachelor’s, Master’s, PhD)?</p>
<p>H₀: las cuatro poblaciones (High School, Bachelor’s, Master’s, PhD) provienen de la misma distribución.
H₁: al menos una población proviene de una distribución distinta.</p>
<p>Para dar inicio al análisis, se separan los valores de Premium Amount en cuatro grupos según la variable Education Level, con el fin de trabajar con cada uno de forma independiente en las pruebas posteriores.</p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb230-1" tabindex="-1"></a>hs <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Education_Level <span class="sc">==</span> <span class="st">&quot;High School&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span>
<span id="cb230-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb230-2" tabindex="-1"></a>bachelors <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Education_Level <span class="sc">==</span> <span class="st">&quot;Bachelor&#39;s&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span>
<span id="cb230-3"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb230-3" tabindex="-1"></a>masters <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Education_Level <span class="sc">==</span> <span class="st">&quot;Master&#39;s&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span>
<span id="cb230-4"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb230-4" tabindex="-1"></a>phd <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Education_Level <span class="sc">==</span> <span class="st">&quot;PhD&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span></code></pre></div>
<p>Antes de decidir qué tipo de prueba aplicar para comparar los cuatro niveles educativos, es necesario verificar si la variable Premium Amount cumple con el supuesto de normalidad en cada uno de los cuatro grupos. Para ello, se emplea la prueba de Lilliefors.</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb231-1" tabindex="-1"></a><span class="fu">lillie.test</span>(hs)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  hs
## D = 0.11531, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb233-1" tabindex="-1"></a><span class="fu">lillie.test</span>(bachelors)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  bachelors
## D = 0.11557, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb235-1" tabindex="-1"></a><span class="fu">lillie.test</span>(masters)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  masters
## D = 0.11667, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb237-1" tabindex="-1"></a><span class="fu">lillie.test</span>(phd)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  phd
## D = 0.11736, p-value &lt; 2.2e-16</code></pre>
<p>Con una confianza del 95%, la prueba de Lilliefors muestra que las distribuciones del Premium Amount para los cuatro niveles educativos: High School (D = 0.11531, p-valor &lt; 0.001), Bachelor’s (D = 0.11557, p-valor &lt; 0.001), Master’s (D = 0.11667, p-valor &lt; 0.001) y PhD (D = 0.11736, p-valor &lt; 0.001), no provienen de una distribución normal, ya que en los cuatro casos el p-valor es considerablemente menor al nivel de significancia establecido.</p>
<p>Dado que no se cumple el supuesto de normalidad en ninguno de los cuatro grupos, no es adecuado aplicar una prueba paramétrica (ANOVA) para comparar medias. Se replantea entonces la hipótesis en términos de mediana (η), coherente con lo que evalúa la prueba de Kruskal-Wallis:</p>
<p>Sea η₁, η₂, η₃ y η₄ las medianas de Premium Amount para High School, Bachelor’s, Master’s y PhD, respectivamente:</p>
<p>H₀: η₁ = η₂ = η₃ = η₄
H₁: al menos una mediana es diferente</p>
<p>Antes de aplicar la prueba de Kruskal-Wallis, se verifica la homogeneidad de varianzas entre los cuatro grupos mediante la prueba de Levene.</p>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb239-1" tabindex="-1"></a><span class="fu">leveneTest</span>(Premium_Amount <span class="sc">~</span> Education_Level, <span class="at">data =</span> df, <span class="at">center =</span> <span class="st">&quot;median&quot;</span>)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = &quot;median&quot;)
##            Df F value  Pr(&gt;F)  
## group       3  2.1127 0.09627 .
##       1199996                  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Con una confianza del 95%, la prueba de Levene indica que no se encuentran diferencias estadísticamente significativas en la varianza del Premium Amount entre los cuatro niveles educativos (F(3) = 2.1127, p-valor = 0.09627), ya que el p-valor es mayor al nivel de significancia establecido. Esto confirma que se cumple el supuesto de homogeneidad de varianzas, por lo que se puede continuar con la prueba de Kruskal-Wallis sin inconvenientes.</p>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb241-1" tabindex="-1"></a><span class="fu">kruskal.test</span>(Premium_Amount <span class="sc">~</span> Education_Level, <span class="at">data =</span> df)</span></code></pre></div>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  Premium_Amount by Education_Level
## Kruskal-Wallis chi-squared = 3.8043, df = 3, p-value = 0.2834</code></pre>
<p>Con una confianza del 95%, la prueba de Kruskal-Wallis indica que no existen diferencias estadísticamente significativas en el Premium Amount entre los cuatro niveles educativos (χ²(3) = 3.8043, p-valor = 0.2834), ya que el p-valor es considerablemente mayor al nivel de significancia establecido. Por lo tanto, no se rechaza H₀.</p>
<p>Calculamos el tamaño del efecto:</p>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb243-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb243-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb243-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb243-2" tabindex="-1"></a>  <span class="fu">kruskal_effsize</span>(Premium_Amount <span class="sc">~</span> Education_Level)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 5
##   .y.                  n     effsize method  magnitude
## * &lt;chr&gt;            &lt;int&gt;       &lt;dbl&gt; &lt;chr&gt;   &lt;ord&gt;    
## 1 Premium_Amount 1200000 0.000000670 eta2[H] small</code></pre>
<p>El tamaño del efecto obtenido fue prácticamente cero (0.00000067), lo que confirma que no hay ningún efecto real entre los niveles educativos sobre el Premium Amount. Esto va en línea con el resultado de Kruskal-Wallis: ni hay diferencia significativa, ni tampoco relevancia práctica entre High School, Bachelor’s, Master’s y PhD.</p>
<p>Finalmente, con una confianza del 95%, tanto la prueba de Kruskal-Wallis (χ²(3) = 3.8043, p-valor = 0.2834) como el tamaño del efecto (prácticamente nulo) indican que no existen diferencias significativas ni relevancia práctica en el Premium Amount entre los cuatro niveles educativos, por lo que no se rechaza H₀.</p>
<p>Pregunta 11: ¿Existen diferencias significativas en el Premium Amount promedio entre las categorías de Occupation (Employed, Self-Employed, Unemployed, No especificado)?</p>
<p>H₀: las cuatro poblaciones (Employed, Self-Employed, Unemployed, No especificado) provienen de la misma distribución.
H₁: al menos una población proviene de una distribución distinta.</p>
<p>Para dar inicio al análisis, se separan los valores de Premium Amount en cuatro grupos según la variable Occupation, con el fin de trabajar con cada uno de forma independiente en las pruebas posteriores.</p>
<div class="sourceCode" id="cb245"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb245-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb245-1" tabindex="-1"></a>empleado <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Occupation <span class="sc">==</span> <span class="st">&quot;Employed&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span>
<span id="cb245-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb245-2" tabindex="-1"></a>independiente <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Occupation <span class="sc">==</span> <span class="st">&quot;Self-Employed&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span>
<span id="cb245-3"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb245-3" tabindex="-1"></a>desempleado <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Occupation <span class="sc">==</span> <span class="st">&quot;Unemployed&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span>
<span id="cb245-4"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb245-4" tabindex="-1"></a>noespecificado <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Occupation <span class="sc">==</span> <span class="st">&quot;No especificado&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span></code></pre></div>
<p>Antes de decidir qué tipo de prueba aplicar para comparar las cuatro categorías de ocupación, es necesario verificar si la variable Premium Amount cumple con el supuesto de normalidad en cada una. Para ello, se emplea la prueba de Lilliefors.</p>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb246-1" tabindex="-1"></a><span class="fu">lillie.test</span>(empleado)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  empleado
## D = 0.11518, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb248-1" tabindex="-1"></a><span class="fu">lillie.test</span>(independiente)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  independiente
## D = 0.11603, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb250-1" tabindex="-1"></a><span class="fu">lillie.test</span>(desempleado)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  desempleado
## D = 0.11644, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb252-1" tabindex="-1"></a><span class="fu">lillie.test</span>(noespecificado)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  noespecificado
## D = 0.11706, p-value &lt; 2.2e-16</code></pre>
<p>Con una confianza del 95%, la prueba de Lilliefors muestra que las distribuciones del Premium Amount para las cuatro categorías de ocupación: Employed (D = 0.11518, p-valor &lt; 0.001), Self-Employed (D = 0.11603, p-valor &lt; 0.001), Unemployed (D = 0.11644, p-valor &lt; 0.001) y No especificado (D = 0.11706, p-valor &lt; 0.001), no provienen de una distribución normal, ya que en los cuatro casos el p-valor es considerablemente menor al nivel de significancia establecido.</p>
<p>Dado que no se cumple el supuesto de normalidad en ninguno de los cuatro grupos, no es adecuado aplicar una prueba paramétrica (ANOVA) para comparar medias. Se replantea entonces la hipótesis en términos de mediana (η), coherente con lo que evalúa la prueba de Kruskal-Wallis:</p>
<p>Sea η₁, η₂, η₃ y η₄ las medianas de Premium Amount para Employed, Self-Employed, Unemployed y No especificado, respectivamente:</p>
<p>H₀: η₁ = η₂ = η₃ = η₄
H₁: al menos una mediana es diferente</p>
<p>Antes de aplicar la prueba de Kruskal-Wallis, se verifica la homogeneidad de varianzas entre los cuatro grupos mediante la prueba de Levene.</p>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb254-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb254-1" tabindex="-1"></a><span class="fu">leveneTest</span>(Premium_Amount <span class="sc">~</span> Occupation, <span class="at">data =</span> df, <span class="at">center =</span> <span class="st">&quot;median&quot;</span>)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = &quot;median&quot;)
##            Df F value    Pr(&gt;F)    
## group       3  14.607 1.648e-09 ***
##       1199996                      
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Con una confianza del 95%, la prueba de Levene indica que sí existen diferencias estadísticamente significativas en la varianza del Premium Amount entre las cuatro categorías de ocupación (F(3) = 14.607, p-valor &lt; 0.001), ya que el p-valor es menor al nivel de significancia establecido. Esto indica que no se cumple el supuesto de homogeneidad de varianzas entre los grupos.</p>
<p>Dado que no se cumple el supuesto de normalidad ni el de homogeneidad de varianzas entre los cuatro grupos, la interpretación de la prueba de Kruskal-Wallis se mantiene en términos de distribución general y no específicamente de medianas:</p>
<p>H₀: las cuatro poblaciones (Employed, Self-Employed, Unemployed, No especificado) provienen de la misma distribución.
H₁: al menos una población proviene de una distribución distinta.</p>
<div class="sourceCode" id="cb256"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb256-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb256-1" tabindex="-1"></a><span class="fu">kruskal.test</span>(Premium_Amount <span class="sc">~</span> Occupation, <span class="at">data =</span> df)</span></code></pre></div>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  Premium_Amount by Occupation
## Kruskal-Wallis chi-squared = 58.061, df = 3, p-value = 1.525e-12</code></pre>
<p>Con una confianza del 95%, la prueba de Kruskal-Wallis indica que existen diferencias estadísticamente significativas en el Premium Amount entre las cuatro categorías de ocupación (χ²(3) = 58.061, p-valor &lt; 0.001), ya que el p-valor es considerablemente menor al nivel de significancia establecido. Por lo tanto, se rechaza H₀.</p>
<p>Calculamos el tamaño del efecto:</p>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb258-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb258-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb258-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb258-2" tabindex="-1"></a>  <span class="fu">kruskal_effsize</span>(Premium_Amount <span class="sc">~</span> Occupation)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 5
##   .y.                  n   effsize method  magnitude
## * &lt;chr&gt;            &lt;int&gt;     &lt;dbl&gt; &lt;chr&gt;   &lt;ord&gt;    
## 1 Premium_Amount 1200000 0.0000459 eta2[H] small</code></pre>
<p>El tamaño del efecto obtenido fue prácticamente nulo (0.0000459), lo que indica que, a pesar de la significancia estadística encontrada, la diferencia entre las categorías de ocupación no tiene relevancia práctica sobre el Premium Amount. Esto es consistente con lo observado en preguntas anteriores (como Health Score): con un tamaño de muestra tan grande (1,200,000 observaciones), incluso diferencias mínimas pueden resultar estadísticamente significativas sin que esto implique una asociación relevante en la práctica.</p>
<p>Sin embargo, dado que la prueba de Kruskal-Wallis resultó significativa, se procede a realizar una prueba post-hoc de comparaciones múltiples por pares (Wilcoxon), con ajuste de Bonferroni, con el fin de identificar cuál o cuáles pares específicos de categorías presentan diferencias significativas entre sí.</p>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb260-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb260-1" tabindex="-1"></a><span class="fu">pairwise.wilcox.test</span>(<span class="at">x =</span> df<span class="sc">$</span>Premium_Amount,</span>
<span id="cb260-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb260-2" tabindex="-1"></a>                      <span class="at">g =</span> df<span class="sc">$</span>Occupation,</span>
<span id="cb260-3"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb260-3" tabindex="-1"></a>                      <span class="at">exact =</span> <span class="cn">FALSE</span>,</span>
<span id="cb260-4"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb260-4" tabindex="-1"></a>                      <span class="at">p.adjust.method =</span> <span class="st">&quot;bonferroni&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using Wilcoxon rank sum test with continuity correction 
## 
## data:  df$Premium_Amount and df$Occupation 
## 
##                 Employed No especificado Self-Employed
## No especificado 2.6e-12  -               -            
## Self-Employed   0.22     3.3e-06         -            
## Unemployed      0.15     8.9e-06         1.00         
## 
## P value adjustment method: bonferroni</code></pre>
<p>Los resultados de la prueba de Wilcoxon por pares con ajuste de Bonferroni muestran que la categoría “No especificado” es la que genera las diferencias significativas encontradas: presenta diferencias estadísticamente significativas frente a Employed (p ajustado &lt; 0.001), frente a Self-Employed (p ajustado &lt; 0.001) y frente a Unemployed (p ajustado &lt; 0.001). En cambio, no se encuentran diferencias significativas entre Employed y Self-Employed (p ajustado = 0.22), entre Employed y Unemployed (p ajustado = 0.15), ni entre Self-Employed y Unemployed (p ajustado = 1.00).</p>
<p>Esto confirma lo observado anteriormente: la diferencia detectada por Kruskal-Wallis no proviene de una distinción real entre los clientes según su situación laboral (Employed, Self-Employed, Unemployed se comportan de forma prácticamente idéntica entre sí), sino específicamente del grupo de clientes cuya ocupación no fue especificada originalmente en los datos. En cualquier caso, como ya se mostró con el tamaño del efecto (prácticamente nulo), esta diferencia carece de relevancia práctica.</p>
<p>En conclusión, con una confianza del 95%, la prueba de Kruskal-Wallis (χ²(3) = 58.061, p-valor &lt; 0.001) indica diferencias estadísticamente significativas en el Premium Amount entre las categorías de ocupación, atribuibles principalmente a la categoría “No especificado” según la prueba de Wilcoxon por pares. Sin embargo, el tamaño del efecto (prácticamente nulo) confirma que esta diferencia no tiene relevancia práctica, y es consistente con el hecho de que, dado el gran tamaño de la muestra, incluso diferencias mínimas pueden alcanzar significancia estadística sin representar una asociación real entre las variables.</p>
<p>Pregunta 12: ¿Existen diferencias significativas en el Premium Amount promedio entre las tres ubicaciones (Rural, Suburban, Urban)?</p>
<p>H₀: las tres poblaciones (Rural, Suburban, Urban) provienen de la misma distribución.
H₁: al menos una población proviene de una distribución distinta.</p>
<p>Para dar inicio al análisis, se separan los valores de Premium Amount en tres grupos según la variable Location, con el fin de trabajar con cada uno de forma independiente en las pruebas posteriores.</p>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb262-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb262-1" tabindex="-1"></a>rural <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Location <span class="sc">==</span> <span class="st">&quot;Rural&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span>
<span id="cb262-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb262-2" tabindex="-1"></a>suburbano <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Location <span class="sc">==</span> <span class="st">&quot;Suburban&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span>
<span id="cb262-3"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb262-3" tabindex="-1"></a>urbano <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Location <span class="sc">==</span> <span class="st">&quot;Urban&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span></code></pre></div>
<p>Antes de decidir qué tipo de prueba aplicar para comparar las tres ubicaciones, es necesario verificar si la variable Premium Amount cumple con el supuesto de normalidad en cada una. Para ello, se emplea la prueba de Lilliefors.</p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb263-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb263-1" tabindex="-1"></a><span class="fu">lillie.test</span>(rural)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  rural
## D = 0.11651, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb265-1" tabindex="-1"></a><span class="fu">lillie.test</span>(suburbano)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  suburbano
## D = 0.11614, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb267-1" tabindex="-1"></a><span class="fu">lillie.test</span>(urbano)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  urbano
## D = 0.11607, p-value &lt; 2.2e-16</code></pre>
<p>Con una confianza del 95%, la prueba de Lilliefors muestra que las distribuciones del Premium Amount para las tres ubicaciones: Rural (D = 0.11651, p-valor &lt; 0.001), Suburban (D = 0.11614, p-valor &lt; 0.001) y Urban (D = 0.11607, p-valor &lt; 0.001), no provienen de una distribución normal, ya que en los tres casos el p-valor es considerablemente menor al nivel de significancia establecido.</p>
<p>Dado que no se cumple el supuesto de normalidad en ninguno de los tres grupos, no es adecuado aplicar una prueba paramétrica (ANOVA) para comparar medias. Se replantea entonces la hipótesis en términos de mediana (η), coherente con lo que evalúa la prueba de Kruskal-Wallis:</p>
<p>Sea η₁, η₂ y η₃ las medianas de Premium Amount para Rural, Suburban y Urban, respectivamente:</p>
<p>H₀: η₁ = η₂ = η₃
H₁: al menos una mediana es diferente</p>
<p>Antes de aplicar la prueba de Kruskal-Wallis, se verifica la homogeneidad de varianzas entre los tres grupos mediante la prueba de Levene.</p>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb269-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb269-1" tabindex="-1"></a><span class="fu">leveneTest</span>(Premium_Amount <span class="sc">~</span> Location, <span class="at">data =</span> df, <span class="at">center =</span> <span class="st">&quot;median&quot;</span>)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = &quot;median&quot;)
##            Df F value Pr(&gt;F)
## group       2  0.5194 0.5949
##       1199997</code></pre>
<p>Con una confianza del 95%, la prueba de Levene indica que no se encuentran diferencias estadísticamente significativas en la varianza del Premium Amount entre las tres ubicaciones (F(2) = 0.5194, p-valor = 0.5949), ya que el p-valor es mayor al nivel de significancia establecido. Esto confirma que se cumple el supuesto de homogeneidad de varianzas, por lo que se puede continuar con la prueba de Kruskal-Wallis sin inconvenientes.</p>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb271-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb271-1" tabindex="-1"></a><span class="fu">kruskal.test</span>(Premium_Amount <span class="sc">~</span> Location, <span class="at">data =</span> df)</span></code></pre></div>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  Premium_Amount by Location
## Kruskal-Wallis chi-squared = 3.4297, df = 2, p-value = 0.18</code></pre>
<p>Con una confianza del 95%, la prueba de Kruskal-Wallis indica que no existen diferencias estadísticamente significativas en el Premium Amount entre las tres ubicaciones (χ²(2) = 3.4297, p-valor = 0.18), ya que el p-valor es considerablemente mayor al nivel de significancia establecido. Por lo tanto, no se rechaza H₀.</p>
<p>Ahora calculamos el tamaño del efecto:</p>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb273-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb273-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb273-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb273-2" tabindex="-1"></a>  <span class="fu">kruskal_effsize</span>(Premium_Amount <span class="sc">~</span> Location)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 5
##   .y.                  n    effsize method  magnitude
## * &lt;chr&gt;            &lt;int&gt;      &lt;dbl&gt; &lt;chr&gt;   &lt;ord&gt;    
## 1 Premium_Amount 1200000 0.00000119 eta2[H] small</code></pre>
<p>El tamaño del efecto obtenido fue prácticamente nulo (0.0000012), lo que confirma que no hay ningún efecto real entre las ubicaciones sobre el Premium Amount. Esto va en línea con el resultado de Kruskal-Wallis: ni hay diferencia significativa, ni tampoco relevancia práctica entre los grupos Rural, Suburban y Urban.</p>
<p>En conclusión, con una confianza del 95%, tanto la prueba de Kruskal-Wallis (χ²(2) = 3.4297, p-valor = 0.18) como el tamaño del efecto (prácticamente nulo) indican que no existen diferencias significativas ni relevancia práctica en el Premium Amount entre las tres ubicaciones, por lo que no se rechaza H₀.</p>
<p>Pregunta 13: ¿Existen diferencias significativas en el Premium Amount promedio entre las categorías de Customer Feedback (Poor, Average, Good)?</p>
<p>H₀: las tres poblaciones (Poor, Average, Good) provienen de la misma distribución.
H₁: al menos una población proviene de una distribución distinta.</p>
<p>Para dar inicio al análisis, se separan los valores de Premium Amount en tres grupos según la variable Customer Feedback, con el fin de trabajar con cada uno de forma independiente en las pruebas posteriores.</p>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb275-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb275-1" tabindex="-1"></a>malo <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Customer_Feedback <span class="sc">==</span> <span class="st">&quot;Poor&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span>
<span id="cb275-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb275-2" tabindex="-1"></a>promedio <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Customer_Feedback <span class="sc">==</span> <span class="st">&quot;Average&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span>
<span id="cb275-3"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb275-3" tabindex="-1"></a>bueno <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Customer_Feedback <span class="sc">==</span> <span class="st">&quot;Good&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span></code></pre></div>
<p>Antes de decidir qué tipo de prueba aplicar para comparar las tres categorías de Customer Feedback, es necesario verificar si la variable Premium Amount cumple con el supuesto de normalidad en cada una. Para ello, se emplea la prueba de Lilliefors.</p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb276-1" tabindex="-1"></a><span class="fu">lillie.test</span>(malo)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  malo
## D = 0.11688, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb278-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb278-1" tabindex="-1"></a><span class="fu">lillie.test</span>(promedio)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  promedio
## D = 0.11484, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb280-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb280-1" tabindex="-1"></a><span class="fu">lillie.test</span>(bueno)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  bueno
## D = 0.11732, p-value &lt; 2.2e-16</code></pre>
<p>Con una confianza del 95%, la prueba de Lilliefors muestra que las distribuciones del Premium Amount para las tres categorías de Customer Feedback: Poor (D = 0.11688, p-valor &lt; 0.001), Average (D = 0.11484, p-valor &lt; 0.001) y Good (D = 0.11732, p-valor &lt; 0.001), no provienen de una distribución normal, ya que en los tres casos el p-valor es considerablemente menor al nivel de significancia establecido.</p>
<p>Dado que no se cumple el supuesto de normalidad en ninguno de los tres grupos, no es adecuado aplicar una prueba paramétrica (ANOVA) para comparar medias. Se replantea entonces la hipótesis en términos de mediana (η), coherente con lo que evalúa la prueba de Kruskal-Wallis:</p>
<p>Sea η₁, η₂ y η₃ las medianas de Premium Amount para Poor, Average y Good, respectivamente:</p>
<p>H₀: η₁ = η₂ = η₃
H₁: al menos una mediana es diferente</p>
<p>Antes de aplicar la prueba de Kruskal-Wallis, se verifica la homogeneidad de varianzas entre los tres grupos mediante la prueba de Levene.</p>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb282-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb282-1" tabindex="-1"></a><span class="fu">leveneTest</span>(Premium_Amount <span class="sc">~</span> Customer_Feedback, <span class="at">data =</span> df, <span class="at">center =</span> <span class="st">&quot;median&quot;</span>)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = &quot;median&quot;)
##            Df F value   Pr(&gt;F)    
## group       2   7.126 0.000804 ***
##       1199997                     
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Con una confianza del 95%, la prueba de Levene indica que sí existen diferencias estadísticamente significativas en la varianza del Premium Amount entre las tres categorías de Customer Feedback (F(2) = 7.126, p-valor = 0.000804), ya que el p-valor es menor al nivel de significancia establecido. Esto indica que no se cumple el supuesto de homogeneidad de varianzas entre los grupos.</p>
<p>Dado que no se cumple el supuesto de normalidad ni el de homogeneidad de varianzas entre los tres grupos, la interpretación de la prueba de Kruskal-Wallis se mantiene en términos de distribución general y no específicamente de medianas:</p>
<p>H₀: las tres poblaciones (Poor, Average, Good) provienen de la misma distribución.
H₁: al menos una población proviene de una distribución distinta.</p>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb284-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb284-1" tabindex="-1"></a><span class="fu">kruskal.test</span>(Premium_Amount <span class="sc">~</span> Customer_Feedback, <span class="at">data =</span> df)</span></code></pre></div>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  Premium_Amount by Customer_Feedback
## Kruskal-Wallis chi-squared = 88.009, df = 2, p-value &lt; 2.2e-16</code></pre>
<p>Con una confianza del 95%, la prueba de Kruskal-Wallis indica que existen diferencias estadísticamente significativas en el Premium Amount entre las tres categorías de Customer Feedback (χ²(2) = 88.009, p-valor &lt; 0.001), ya que el p-valor es considerablemente menor al nivel de significancia establecido. Por lo tanto, se rechaza H₀.</p>
<p>Calculamos el tamaño del efecto:</p>
<div class="sourceCode" id="cb286"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb286-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb286-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb286-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb286-2" tabindex="-1"></a>  <span class="fu">kruskal_effsize</span>(Premium_Amount <span class="sc">~</span> Customer_Feedback)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 5
##   .y.                  n   effsize method  magnitude
## * &lt;chr&gt;            &lt;int&gt;     &lt;dbl&gt; &lt;chr&gt;   &lt;ord&gt;    
## 1 Premium_Amount 1200000 0.0000717 eta2[H] small</code></pre>
<p>El tamaño del efecto obtenido fue prácticamente nulo (0.0000717), lo que indica que, a pesar de la significancia estadística encontrada, la diferencia entre las categorías de Customer Feedback no tiene relevancia práctica sobre el Premium Amount. Esto es consistente con el patrón observado en Occupation: con un tamaño de muestra tan grande (1,200,000 observaciones), incluso diferencias mínimas pueden resultar estadísticamente significativas sin que esto implique una asociación relevante en la práctica.</p>
<p>Dado que la prueba de Kruskal-Wallis resultó significativa, se procede a realizar una prueba post-hoc de comparaciones múltiples por pares (Wilcoxon), con ajuste de Bonferroni, con el fin de identificar cuál o cuáles pares específicos de categorías presentan diferencias significativas entre sí.</p>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb288-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb288-1" tabindex="-1"></a><span class="fu">pairwise.wilcox.test</span>(<span class="at">x =</span> df<span class="sc">$</span>Premium_Amount, <span class="at">g =</span> df<span class="sc">$</span>Customer_Feedback, <span class="at">exact =</span> <span class="cn">FALSE</span>, <span class="at">p.adjust.method =</span> <span class="st">&quot;bonferroni&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Pairwise comparisons using Wilcoxon rank sum test with continuity correction 
## 
## data:  df$Premium_Amount and df$Customer_Feedback 
## 
##         Poor    Average
## Average 1.5e-12 -      
## Good    0.55    &lt; 2e-16
## 
## P value adjustment method: bonferroni</code></pre>
<p>Los resultados de la prueba de Wilcoxon por pares con ajuste de Bonferroni muestran que la categoría “Average” es la que genera las diferencias significativas encontradas: presenta diferencias estadísticamente significativas frente a Good (p ajustado &lt; 0.001) y frente a Poor (p ajustado &lt; 0.001). En cambio, no se encuentra una diferencia significativa entre Good y Poor (p ajustado = 0.55).</p>
<p>Esto confirma lo observado anteriormente: la diferencia detectada por Kruskal-Wallis no proviene de una distinción entre una opinión positiva y una negativa (Good y Poor se comportan de forma similar entre sí), sino específicamente del grupo de clientes cuyo feedback fue clasificado como “Average”. En cualquier caso, como ya se mostró con el tamaño del efecto (prácticamente nulo), esta diferencia carece de relevancia práctica</p>
<p>En conclusión, con una confianza del 95%, la prueba de Kruskal-Wallis (χ²(2) = 88.009, p-valor &lt; 0.001) indica diferencias estadísticamente significativas en el Premium Amount entre las categorías de Customer Feedback, atribuibles principalmente a la categoría “Average” según la prueba de Wilcoxon por pares. Sin embargo, el tamaño del efecto (prácticamente nulo) confirma que esta diferencia no tiene relevancia práctica, y es consistente con el hecho de que, dado el gran tamaño de la muestra, incluso diferencias mínimas pueden alcanzar significancia estadística sin representar una asociación real entre las variables.</p>
<p>Pregunta 14: ¿Existen diferencias significativas en el Premium Amount promedio entre los tres tipos de propiedad (Apartment, Condo, House)?</p>
<p>H₀: las tres poblaciones (Apartment, Condo, House) provienen de la misma distribución.
H₁: al menos una población proviene de una distribución distinta.</p>
<p>Para dar inicio al análisis, se separan los valores de Premium Amount en tres grupos según la variable Property Type, con el fin de trabajar con cada uno de forma independiente en las pruebas posteriores.</p>
<div class="sourceCode" id="cb290"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb290-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb290-1" tabindex="-1"></a>apartamento <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Property_Type <span class="sc">==</span> <span class="st">&quot;Apartment&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span>
<span id="cb290-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb290-2" tabindex="-1"></a>condominio <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Property_Type <span class="sc">==</span> <span class="st">&quot;Condo&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span>
<span id="cb290-3"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb290-3" tabindex="-1"></a>casa <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Property_Type <span class="sc">==</span> <span class="st">&quot;House&quot;</span>) <span class="sc">%&gt;%</span> <span class="fu">pull</span>(Premium_Amount)</span></code></pre></div>
<p>Antes de decidir qué tipo de prueba aplicar para comparar los tres tipos de propiedad, es necesario verificar si la variable Premium Amount cumple con el supuesto de normalidad en cada uno. Para ello, se emplea la prueba de Lilliefors.</p>
<div class="sourceCode" id="cb291"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb291-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb291-1" tabindex="-1"></a><span class="fu">lillie.test</span>(apartamento)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  apartamento
## D = 0.11589, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb293-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb293-1" tabindex="-1"></a><span class="fu">lillie.test</span>(condominio)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  condominio
## D = 0.11701, p-value &lt; 2.2e-16</code></pre>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb295-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb295-1" tabindex="-1"></a><span class="fu">lillie.test</span>(casa)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  casa
## D = 0.11582, p-value &lt; 2.2e-16</code></pre>
<p>Con una confianza del 95%, la prueba de Lilliefors muestra que las distribuciones del Premium Amount para los tres tipos de propiedad: Apartment (D = 0.11589, p-valor &lt; 0.001), Condo (D = 0.11701, p-valor &lt; 0.001) y House (D = 0.11582, p-valor &lt; 0.001), no provienen de una distribución normal, ya que en los tres casos el p-valor es considerablemente menor al nivel de significancia establecido.</p>
<p>Dado que no se cumple el supuesto de normalidad en ninguno de los tres grupos, no es adecuado aplicar una prueba paramétrica (ANOVA) para comparar medias. Se replantea entonces la hipótesis en términos de mediana (η), coherente con lo que evalúa la prueba de Kruskal-Wallis:</p>
<p>Sea η₁, η₂ y η₃ las medianas de Premium Amount para Apartment, Condo y House, respectivamente:</p>
<p>H₀: η₁ = η₂ = η₃
H₁: al menos una mediana es diferente</p>
<p>Antes de aplicar la prueba de Kruskal-Wallis, se verifica la homogeneidad de varianzas entre los tres grupos mediante la prueba de Levene.</p>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb297-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb297-1" tabindex="-1"></a><span class="fu">leveneTest</span>(Premium_Amount <span class="sc">~</span> Property_Type, <span class="at">data =</span> df, <span class="at">center =</span> <span class="st">&quot;median&quot;</span>)</span></code></pre></div>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center = &quot;median&quot;)
##            Df F value   Pr(&gt;F)   
## group       2  5.7774 0.003097 **
##       1199997                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Con una confianza del 95%, la prueba de Levene indica que sí existen diferencias estadísticamente significativas en la varianza del Premium Amount entre los tres tipos de propiedad (F(2) = 5.7774, p-valor = 0.003097), ya que el p-valor es menor al nivel de significancia establecido. Esto indica que no se cumple el supuesto de homogeneidad de varianzas entre los grupos.</p>
<p>Dado que no se cumple el supuesto de normalidad ni el de homogeneidad de varianzas entre los tres grupos, la interpretación de la prueba de Kruskal-Wallis se mantiene en términos de distribución general y no específicamente de medianas:</p>
<p>H₀: las tres poblaciones (Apartment, Condo, House) provienen de la misma distribución.
H₁: al menos una población proviene de una distribución distinta.</p>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb299-1" tabindex="-1"></a><span class="fu">kruskal.test</span>(Premium_Amount <span class="sc">~</span> Property_Type, <span class="at">data =</span> df)</span></code></pre></div>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  Premium_Amount by Property_Type
## Kruskal-Wallis chi-squared = 1.7384, df = 2, p-value = 0.4193</code></pre>
<p>Con una confianza del 95%, la prueba de Kruskal-Wallis indica que no existen diferencias estadísticamente significativas en el Premium Amount entre los tres tipos de propiedad (χ²(2) = 1.7384, p-valor = 0.4193), ya que el p-valor es considerablemente mayor al nivel de significancia establecido. Por lo tanto, no se rechaza H₀.</p>
<p>Sin embargo, calculamos el tamaño del efecto:</p>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb301-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb301-2"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb301-2" tabindex="-1"></a>  <span class="fu">kruskal_effsize</span>(Premium_Amount <span class="sc">~</span> Property_Type)</span></code></pre></div>
<pre><code>## # A tibble: 1 x 5
##   .y.                  n effsize method  magnitude
## * &lt;chr&gt;            &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;   &lt;ord&gt;    
## 1 Premium_Amount 1200000       0 eta2[H] small</code></pre>
<p>El tamaño del efecto obtenido fue de 0, lo que confirma que no hay ningún efecto real entre los tipos de propiedad sobre el Premium Amount. Esto va en línea con el resultado de Kruskal-Wallis: ni hay diferencia significativa, ni tampoco relevancia práctica entre los grupos Apartment, Condo y House.</p>
<p>En conclusión, con una confianza del 95%, tanto la prueba de Kruskal-Wallis (χ²(2) = 1.7384, p-valor = 0.4193) como el tamaño del efecto (valor de 0) indican que no existen diferencias significativas ni relevancia práctica en el Premium Amount entre los tres tipos de propiedad, por lo que no se rechaza H₀.</p>
<p>Pregunta 15: ¿Existe una correlación significativa entre Age y Premium Amount?</p>
<p>Sea ρ el coeficiente de correlación poblacional entre Age y Premium Amount.</p>
<p>H₀: ρ = 0 (no existe correlación entre las variables)
H₁: ρ ≠ 0 (existe correlación entre las variables)</p>
<p>Como Premium Amount ya sabemos que no es normal (lo hemos confirmado en todas las preguntas anteriores), solo falta verificar Age. Esto decide si usamos Pearson o Spearman.</p>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb303-1" tabindex="-1"></a><span class="fu">lillie.test</span>(df<span class="sc">$</span>Age)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  df$Age
## D = 0.06621, p-value &lt; 2.2e-16</code></pre>
<p>Con una confianza del 95%, la prueba de Lilliefors muestra que ni Age (D = 0.06621, p-valor &lt; 0.001) ni Premium Amount (D = 0.11624, p-valor &lt; 0.001, ya verificado previamente) provienen de una distribución normal, ya que en ambos casos el p-valor es considerablemente menor al nivel de significancia establecido.</p>
<p>Dado que ninguna de las dos variables cumple el supuesto de normalidad, se utiliza el coeficiente de correlación de Spearman para evaluar la relación entre Age y Premium Amount.</p>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb305-1" tabindex="-1"></a><span class="fu">cor.test</span>(df<span class="sc">$</span>Age, df<span class="sc">$</span>Premium_Amount, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>)</span></code></pre></div>
<pre><code>## Warning in cor.test.default(df$Age, df$Premium_Amount, method = &quot;spearman&quot;):
## Cannot compute exact p-value with ties</code></pre>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  df$Age and df$Premium_Amount
## S = 2.8867e+17, p-value = 0.01129
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##          rho 
## -0.002312819</code></pre>
<p>Con una confianza del 95%, la prueba de correlación de Spearman indica que existe una correlación estadísticamente significativa entre Age y Premium Amount (S = 2.8867e+17, p-valor = 0.01129, rho = -0.0023), ya que el p-valor es menor al nivel de significancia establecido. Por lo tanto, se rechaza H₀. Sin embargo, el valor del coeficiente de correlación (rho = -0.0023) es extremadamente bajo, lo que indica que, a pesar de ser significativa desde el punto de vista estadístico, la relación entre ambas variables es prácticamente nula en términos prácticos.</p>
<p>En conclusión,con una confianza del 95%, la prueba de correlación de Spearman detecta una asociación estadísticamente significativa entre Age y Premium Amount (rho = -0.0023, p-valor = 0.01129), pero el coeficiente de correlación es tan cercano a cero que carece de relevancia práctica, en línea con el patrón detectado en el resto del análisis: dado el gran tamaño de la muestra, incluso relaciones prácticamente inexistentes pueden alcanzar significancia estadística.</p>
<p>Pregunta 16: ¿Existe una correlación significativa entre Annual Income y Premium Amount?</p>
<p>Sea ρ el coeficiente de correlación poblacional entre Annual Income y Premium Amount.</p>
<p>H₀: ρ = 0 (no existe correlación entre las variables)
H₁: ρ ≠ 0 (existe correlación entre las variables)</p>
<p>Antes de decidir qué coeficiente de correlación utilizar (Pearson o Spearman), es necesario verificar si ambas variables cumplen el supuesto de normalidad. Dado que Premium Amount ya se confirmó como no normal en preguntas anteriores, resta verificar Annual Income. Para ello, se aplica la prueba de Lilliefors.</p>
<div class="sourceCode" id="cb308"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb308-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb308-1" tabindex="-1"></a><span class="fu">lillie.test</span>(df<span class="sc">$</span>Annual_Income)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  df$Annual_Income
## D = 0.15271, p-value &lt; 2.2e-16</code></pre>
<p>Con una confianza del 95%, la prueba de Lilliefors muestra que ni Annual Income (D = 0.15271, p-valor &lt; 0.001) ni Premium Amount (D = 0.11624, p-valor &lt; 0.001, ya verificado previamente) provienen de una distribución normal, ya que en ambos casos el p-valor es considerablemente menor al nivel de significancia establecido.</p>
<p>Dado que ninguna de las dos variables cumple el supuesto de normalidad, se utiliza el coeficiente de correlación de Spearman para evaluar la relación entre Annual Income y Premium Amount.</p>
<div class="sourceCode" id="cb310"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb310-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb310-1" tabindex="-1"></a><span class="fu">cor.test</span>(df<span class="sc">$</span>Annual_Income, df<span class="sc">$</span>Premium_Amount, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>)</span></code></pre></div>
<pre><code>## Warning in cor.test.default(df$Annual_Income, df$Premium_Amount, method =
## &quot;spearman&quot;): Cannot compute exact p-value with ties</code></pre>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  df$Annual_Income and df$Premium_Amount
## S = 3.0523e+17, p-value &lt; 2.2e-16
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##         rho 
## -0.05983851</code></pre>
<p>Con una confianza del 95%, la prueba de correlación de Spearman indica que existe una correlación estadísticamente significativa entre Annual Income y Premium Amount (S = 3.0523e+17, p-valor &lt; 0.001, rho = -0.0598), ya que el p-valor es considerablemente menor al nivel de significancia establecido. Por lo tanto, se rechaza H₀. Sin embargo, el valor del coeficiente de correlación (rho = -0.0598) sigue siendo bastante bajo, aunque un poco mayor que en el caso de Age, lo que indica que, a pesar de ser significativa desde el punto de vista estadístico, la relación entre ambas variables continúa siendo prácticamente nula en términos prácticos.</p>
<p>En conclusión, con una confianza del 95%, la prueba de correlación de Spearman detecta una asociación estadísticamente significativa entre Annual Income y Premium Amount (rho = -0.0598, p-valor &lt; 0.001), pero el coeficiente de correlación es demasiado bajo para tener relevancia práctica, en línea con el patrón detectado en el resto del análisis: dado el gran tamaño de la muestra, incluso relaciones muy débiles pueden alcanzar significancia estadística.</p>
<p>Pregunta 17: ¿Existe una correlación significativa entre Previous Claims y Premium Amount?</p>
<p>Sea ρ el coeficiente de correlación poblacional entre Previous Claims y Premium Amount.</p>
<p>H₀: ρ = 0 (no existe correlación entre las variables)
H₁: ρ ≠ 0 (existe correlación entre las variables)</p>
<p>Antes de decidir qué coeficiente de correlación utilizar (Pearson o Spearman), es necesario verificar si ambas variables cumplen el supuesto de normalidad. Dado que Premium Amount ya se confirmó como no normal en preguntas anteriores, resta verificar Previous Claims. Para ello, se aplica la prueba de Lilliefors.</p>
<div class="sourceCode" id="cb313"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb313-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb313-1" tabindex="-1"></a><span class="fu">lillie.test</span>(df<span class="sc">$</span>Previous_Claims)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  df$Previous_Claims
## D = 0.32895, p-value &lt; 2.2e-16</code></pre>
<p>Con una confianza del 95%, la prueba de Lilliefors muestra que ni Previous Claims (D = 0.32895, p-valor &lt; 0.001) ni Premium Amount (D = 0.11624, p-valor &lt; 0.001, ya verificado previamente) provienen de una distribución normal, ya que en ambos casos el p-valor es considerablemente menor al nivel de significancia establecido. El valor de D en Previous Claims es notablemente más alto que en las variables anteriores, lo cual es coherente con su fuerte sesgo hacia la derecha observado en el EDA (la mayoría de los clientes concentrados en 0 reclamos).</p>
<p>Dado que ninguna de las dos variables cumple el supuesto de normalidad, se utiliza el coeficiente de correlación de Spearman para evaluar la relación entre Previous Claims y Premium Amount.</p>
<div class="sourceCode" id="cb315"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb315-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb315-1" tabindex="-1"></a><span class="fu">cor.test</span>(df<span class="sc">$</span>Previous_Claims, df<span class="sc">$</span>Premium_Amount, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>)</span></code></pre></div>
<pre><code>## Warning in cor.test.default(df$Previous_Claims, df$Premium_Amount, method =
## &quot;spearman&quot;): Cannot compute exact p-value with ties</code></pre>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  df$Previous_Claims and df$Premium_Amount
## S = 2.7674e+17, p-value &lt; 2.2e-16
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##        rho 
## 0.03910466</code></pre>
<p>Se rechaza H₀ dado que la prueba de Spearman resulta significativa (rho = 0.0391, p-valor &lt; 0.001). Como ha ocurrido con las demás variables numéricas analizadas, este resultado es producto del tamaño de la muestra más que de una asociación real entre la cantidad de reclamos previos y el monto de la prima.</p>
<p>En conclusión, con una confianza del 95%, la prueba de correlación de Spearman detecta una asociación estadísticamente significativa entre Previous Claims y Premium Amount (rho = 0.0391, p-valor &lt; 0.001), sin embargo, se trata de un coeficiente tan bajo que no representa una relación de relevancia práctica. Esto reafirma el patrón visto a lo largo del análisis: el gran tamaño de la muestra permite que asociaciones prácticamente inexistentes terminen siendo estadísticamente significativas.</p>
<p>Pregunta 18: ¿Existe una correlación significativa entre Vehicle Age y Premium Amount?</p>
<p>Sea ρ el coeficiente de correlación poblacional entre Vehicle Age y Premium Amount.</p>
<p>H₀: ρ = 0 (no existe correlación entre las variables)
H₁: ρ ≠ 0 (existe correlación entre las variables)</p>
<p>Antes de decidir qué coeficiente de correlación utilizar (Pearson o Spearman), es necesario verificar si ambas variables cumplen el supuesto de normalidad. Dado que Premium Amount ya se confirmó como no normal en preguntas anteriores, resta verificar Vehicle Age. Para ello, se aplica la prueba de Lilliefors.</p>
<div class="sourceCode" id="cb318"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb318-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb318-1" tabindex="-1"></a><span class="fu">lillie.test</span>(df<span class="sc">$</span>Vehicle_Age)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  df$Vehicle_Age
## D = 0.083798, p-value &lt; 2.2e-16</code></pre>
<p>Con una confianza del 95%, la prueba de Lilliefors muestra que ni Vehicle Age (D = 0.083798, p-valor &lt; 0.001) ni Premium Amount (D = 0.11624, p-valor &lt; 0.001, ya verificado previamente) provienen de una distribución normal, ya que en ambos casos el p-valor es considerablemente menor al nivel de significancia establecido.</p>
<p>Dado que ninguna de las dos variables cumple el supuesto de normalidad, se utiliza el coeficiente de correlación de Spearman para evaluar la relación entre Vehicle Age y Premium Amount.</p>
<div class="sourceCode" id="cb320"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb320-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb320-1" tabindex="-1"></a><span class="fu">cor.test</span>(df<span class="sc">$</span>Vehicle_Age, df<span class="sc">$</span>Premium_Amount, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>)</span></code></pre></div>
<pre><code>## Warning in cor.test.default(df$Vehicle_Age, df$Premium_Amount, method =
## &quot;spearman&quot;): Cannot compute exact p-value with ties</code></pre>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  df$Vehicle_Age and df$Premium_Amount
## S = 2.8775e+17, p-value = 0.3402
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##          rho 
## 0.0008706866</code></pre>
<p>La prueba de correlación de Spearman entre Vehicle Age y Premium Amount arroja un p-valor de 0.3402, considerablemente mayor al nivel de significancia establecido, por lo que no se rechaza H₀. El coeficiente obtenido (rho = 0.0009) es prácticamente cero, confirmando que no existe ninguna relación entre la antigüedad del vehículo y el monto de la prima.</p>
<p>En conclusión, con una confianza del 95%, no hay evidencia suficiente para afirmar que existe una correlación entre Vehicle Age y Premium Amount (rho = 0.0009, p-valor = 0.3402), por lo que no se rechaza H₀. A diferencia de las variables anteriores, aquí ni siquiera el gran tamaño de la muestra fue suficiente para alcanzar significancia estadística, lo que refuerza la ausencia de relación entre estas dos variables.</p>
<p>Pregunta 19: ¿Existe una correlación significativa entre Credit Score y Premium Amount?</p>
<p>Sea ρ el coeficiente de correlación poblacional entre Credit Score y Premium Amount.</p>
<p>H₀: ρ = 0 (no existe correlación entre las variables)
H₁: ρ ≠ 0 (existe correlación entre las variables)</p>
<p>Antes de decidir qué coeficiente de correlación utilizar (Pearson o Spearman), es necesario verificar si ambas variables cumplen el supuesto de normalidad. Dado que Premium Amount ya se confirmó como no normal en preguntas anteriores, resta verificar Credit Score. Para ello, se aplica la prueba de Lilliefors.</p>
<div class="sourceCode" id="cb323"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb323-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb323-1" tabindex="-1"></a><span class="fu">lillie.test</span>(df<span class="sc">$</span>Credit_Score)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  df$Credit_Score
## D = 0.064415, p-value &lt; 2.2e-16</code></pre>
<p>Con una confianza del 95%, la prueba de Lilliefors muestra que ni Credit Score (D = 0.064415, p-valor &lt; 0.001) ni Premium Amount (D = 0.11624, p-valor &lt; 0.001, ya verificado previamente) provienen de una distribución normal, ya que en ambos casos el p-valor es considerablemente menor al nivel de significancia establecido.</p>
<p>Dado que ninguna de las dos variables cumple el supuesto de normalidad, se utiliza el coeficiente de correlación de Spearman para evaluar la relación entre Credit Score y Premium Amount.</p>
<div class="sourceCode" id="cb325"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb325-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb325-1" tabindex="-1"></a><span class="fu">cor.test</span>(df<span class="sc">$</span>Credit_Score, df<span class="sc">$</span>Premium_Amount, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>)</span></code></pre></div>
<pre><code>## Warning in cor.test.default(df$Credit_Score, df$Premium_Amount, method =
## &quot;spearman&quot;): Cannot compute exact p-value with ties</code></pre>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  df$Credit_Score and df$Premium_Amount
## S = 2.9989e+17, p-value &lt; 2.2e-16
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##       rho 
## -0.041274</code></pre>
<p>La prueba de correlación de Spearman entre Credit Score y Premium Amount resulta significativa (S = 2.9989e+17, p-valor &lt; 0.001, rho = -0.0413), por lo que se rechaza H₀. No obstante, el coeficiente sigue siendo muy bajo, en la misma línea que Annual Income y Previous Claims, indicando que aunque existe significancia estadística, la relación real entre el puntaje crediticio y el monto de la prima es insignificante.</p>
<p>En conclusión, con una confianza del 95%, se rechaza H₀ ante la correlación significativa detectada entre Credit Score y Premium Amount (rho = -0.0413, p-valor &lt; 0.001), pero dado lo cercano a cero del coeficiente, esta asociación no tiene ningún valor práctico y responde una vez más al tamaño masivo de la muestra.</p>
<p>Pregunta 20: ¿Existe una correlación significativa entre Insurance Duration y Premium Amount?</p>
<p>Sea ρ el coeficiente de correlación poblacional entre Insurance Duration y Premium Amount.</p>
<p>H₀: ρ = 0 (no existe correlación entre las variables)
H₁: ρ ≠ 0 (existe correlación entre las variables)</p>
<p>Antes de decidir qué coeficiente de correlación utilizar (Pearson o Spearman), es necesario verificar si ambas variables cumplen el supuesto de normalidad. Dado que Premium Amount ya se confirmó como no normal en preguntas anteriores, resta verificar Insurance Duration. Para ello, se aplica la prueba de Lilliefors.</p>
<div class="sourceCode" id="cb328"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb328-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb328-1" tabindex="-1"></a><span class="fu">lillie.test</span>(df<span class="sc">$</span>Insurance_Duration)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  df$Insurance_Duration
## D = 0.11518, p-value &lt; 2.2e-16</code></pre>
<p>Con una confianza del 95%, la prueba de Lilliefors muestra que ni Insurance Duration (D = 0.11518, p-valor &lt; 0.001) ni Premium Amount (D = 0.11624, p-valor &lt; 0.001, ya verificado previamente) provienen de una distribución normal, ya que en ambos casos el p-valor es considerablemente menor al nivel de significancia establecido.</p>
<p>Dado que ninguna de las dos variables cumple el supuesto de normalidad, se utiliza el coeficiente de correlación de Spearman para evaluar la relación entre Insurance Duration y Premium Amount.</p>
<div class="sourceCode" id="cb330"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb330-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb330-1" tabindex="-1"></a><span class="fu">cor.test</span>(df<span class="sc">$</span>Insurance_Duration, df<span class="sc">$</span>Premium_Amount, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>)</span></code></pre></div>
<pre><code>## Warning in cor.test.default(df$Insurance_Duration, df$Premium_Amount, method =
## &quot;spearman&quot;): Cannot compute exact p-value with ties</code></pre>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  df$Insurance_Duration and df$Premium_Amount
## S = 2.8802e+17, p-value = 0.9381
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##           rho 
## -7.085295e-05</code></pre>
<p>La prueba de correlación de Spearman entre Insurance Duration y Premium Amount arroja un p-valor de 0.9381, muy por encima del nivel de significancia establecido, por lo que no se rechaza H₀. El coeficiente obtenido (rho = -0.00007) es esencialmente cero, mostrando que no hay absolutamente ninguna asociación entre la duración de la póliza y el monto de la prima.</p>
<p>En conclusión, con una confianza del 95%, no se encuentra evidencia de correlación entre Insurance Duration y Premium Amount (rho = -0.00007, p-valor = 0.9381), por lo que no se rechaza H₀. De todas las variables numéricas analizadas hasta ahora, esta es la que presenta el coeficiente más cercano a cero, dejando claro que la duración de la póliza no tiene ninguna incidencia sobre el monto que paga el cliente.</p>
<p>Pregunta 21: ¿Existe una correlación significativa entre Number of Dependents y Premium Amount?</p>
<p>Sea ρ el coeficiente de correlación poblacional entre Number of Dependents y Premium Amount.</p>
<p>H₀: ρ = 0 (no existe correlación entre las variables)
H₁: ρ ≠ 0 (existe correlación entre las variables)</p>
<p>Antes de decidir qué coeficiente de correlación utilizar (Pearson o Spearman), es necesario verificar si ambas variables cumplen el supuesto de normalidad. Dado que Premium Amount ya se confirmó como no normal en preguntas anteriores, resta verificar Number of Dependents. Para ello, se aplica la prueba de Lilliefors.</p>
<div class="sourceCode" id="cb333"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb333-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb333-1" tabindex="-1"></a><span class="fu">lillie.test</span>(df<span class="sc">$</span>Number_of_Dependents)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  df$Number_of_Dependents
## D = 0.20221, p-value &lt; 2.2e-16</code></pre>
<p>Con una confianza del 95%, la prueba de Lilliefors muestra que ni Number of Dependents (D = 0.20221, p-valor &lt; 0.001) ni Premium Amount (D = 0.11624, p-valor &lt; 0.001, ya verificado previamente) provienen de una distribución normal, ya que en ambos casos el p-valor es considerablemente menor al nivel de significancia establecido.</p>
<p>Dado que ninguna de las dos variables cumple el supuesto de normalidad, se utiliza el coeficiente de correlación de Spearman para evaluar la relación entre Number of Dependents y Premium Amount.</p>
<div class="sourceCode" id="cb335"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb335-1"><a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#cb335-1" tabindex="-1"></a><span class="fu">cor.test</span>(df<span class="sc">$</span>Number_of_Dependents, df<span class="sc">$</span>Premium_Amount, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>)</span></code></pre></div>
<pre><code>## Warning in cor.test.default(df$Number_of_Dependents, df$Premium_Amount, :
## Cannot compute exact p-value with ties</code></pre>
<pre><code>## 
##  Spearman&#39;s rank correlation rho
## 
## data:  df$Number_of_Dependents and df$Premium_Amount
## S = 2.8811e+17, p-value = 0.6703
## alternative hypothesis: true rho is not equal to 0
## sample estimates:
##           rho 
## -0.0003886878</code></pre>
<p>La prueba de correlación de Spearman entre Number of Dependents y Premium Amount arroja un p-valor de 0.6703, muy por encima del nivel de significancia establecido, por lo que no se rechaza H₀. El coeficiente obtenido (rho = -0.0004) es esencialmente cero, mostrando que no hay ninguna asociación entre la cantidad de dependientes de un cliente y el monto de su prima.</p>
<p>En conclusión, con una confianza del 95%, no se encuentra evidencia de correlación entre Number of Dependents y Premium Amount (rho = -0.0004, p-valor = 0.6703), por lo que no se rechaza H₀. Al igual que ocurrió con Insurance Duration y Vehicle Age, esta variable no muestra ningún tipo de relación con el monto de la prima.</p>
<div id="conclusiones" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Conclusiones<a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#conclusiones" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Retomando la pregunta que guio este capítulo —¿cuáles de las 18 variables predictoras presentan una asociación estadísticamente significativa <strong>y</strong> prácticamente relevante con Premium Amount?—, la respuesta es clara: <strong>ninguna cumple ambos criterios a la vez</strong>. La Tabla <a href="pruebas-de-hipótesis-paramétricas-y-no-paramétricas.html#tab:resumen">3.1</a> resume los resultados de las 21 pruebas realizadas.</p>
<pre><code>## Warning: package &#39;knitr&#39; was built under R version 4.5.3</code></pre>
<table style="width:100%;">
<caption><span id="tab:resumen">Table 3.1: </span>Resumen de las 21 pruebas de hip&lt;U+00F3&gt;tesis realizadas</caption>
<colgroup>
<col width="34%" />
<col width="14%" />
<col width="7%" />
<col width="13%" />
<col width="29%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Variable / Relaci&lt;U+00F3&gt;n</th>
<th align="left">Prueba</th>
<th align="left">p-valor</th>
<th align="left">Efecto</th>
<th align="left">Conclusi&lt;U+00F3&gt;n</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Smoking Status</td>
<td align="left">Mann-Whitney</td>
<td align="left">0.680</td>
<td align="left">r = 0.0004</td>
<td align="left">No significativo</td>
</tr>
<tr class="even">
<td align="left">Policy Type</td>
<td align="left">Kruskal-Wallis</td>
<td align="left">0.385</td>
<td align="left">eta2 = 0</td>
<td align="left">No significativo</td>
</tr>
<tr class="odd">
<td align="left">Health Score</td>
<td align="left">Spearman</td>
<td align="left">&lt; 0.001</td>
<td align="left">rho = 0.016</td>
<td align="left">Significativo, sin relevancia</td>
</tr>
<tr class="even">
<td align="left">Smoking Status - Policy Type</td>
<td align="left">Chi-cuadrado</td>
<td align="left">0.070</td>
<td align="left">-</td>
<td align="left">No significativo</td>
</tr>
<tr class="odd">
<td align="left">Gender</td>
<td align="left">Mann-Whitney</td>
<td align="left">0.894</td>
<td align="left">r = 0.0001</td>
<td align="left">No significativo</td>
</tr>
<tr class="even">
<td align="left">Exercise Frequency</td>
<td align="left">Kruskal-Wallis</td>
<td align="left">0.431</td>
<td align="left">eta2 = 0</td>
<td align="left">No significativo</td>
</tr>
<tr class="odd">
<td align="left">Annual Income - Vehicle Age</td>
<td align="left">Spearman</td>
<td align="left">0.712</td>
<td align="left">rho = -0.0003</td>
<td align="left">No significativo</td>
</tr>
<tr class="even">
<td align="left">Smoking Status - Exercise Frequency</td>
<td align="left">Chi-cuadrado</td>
<td align="left">0.283</td>
<td align="left">-</td>
<td align="left">No significativo</td>
</tr>
<tr class="odd">
<td align="left">Marital Status</td>
<td align="left">Kruskal-Wallis</td>
<td align="left">0.558</td>
<td align="left">eta2 = 0</td>
<td align="left">No significativo</td>
</tr>
<tr class="even">
<td align="left">Education Level</td>
<td align="left">Kruskal-Wallis</td>
<td align="left">0.283</td>
<td align="left">eta2 ~ 0</td>
<td align="left">No significativo</td>
</tr>
<tr class="odd">
<td align="left">Occupation</td>
<td align="left">Kruskal-Wallis</td>
<td align="left">&lt; 0.001</td>
<td align="left">eta2 ~ 0</td>
<td align="left">Significativo, sin relevancia</td>
</tr>
<tr class="even">
<td align="left">Location</td>
<td align="left">Kruskal-Wallis</td>
<td align="left">0.180</td>
<td align="left">eta2 ~ 0</td>
<td align="left">No significativo</td>
</tr>
<tr class="odd">
<td align="left">Customer Feedback</td>
<td align="left">Kruskal-Wallis</td>
<td align="left">&lt; 0.001</td>
<td align="left">eta2 ~ 0</td>
<td align="left">Significativo, sin relevancia</td>
</tr>
<tr class="even">
<td align="left">Property Type</td>
<td align="left">Kruskal-Wallis</td>
<td align="left">0.419</td>
<td align="left">eta2 = 0</td>
<td align="left">No significativo</td>
</tr>
<tr class="odd">
<td align="left">Age</td>
<td align="left">Spearman</td>
<td align="left">0.011</td>
<td align="left">rho = -0.002</td>
<td align="left">Significativo, sin relevancia</td>
</tr>
<tr class="even">
<td align="left">Annual Income</td>
<td align="left">Spearman</td>
<td align="left">&lt; 0.001</td>
<td align="left">rho = -0.060</td>
<td align="left">Significativo, sin relevancia</td>
</tr>
<tr class="odd">
<td align="left">Previous Claims</td>
<td align="left">Spearman</td>
<td align="left">&lt; 0.001</td>
<td align="left">rho = 0.039</td>
<td align="left">Significativo, sin relevancia</td>
</tr>
<tr class="even">
<td align="left">Vehicle Age</td>
<td align="left">Spearman</td>
<td align="left">0.340</td>
<td align="left">rho = 0.001</td>
<td align="left">No significativo</td>
</tr>
<tr class="odd">
<td align="left">Credit Score</td>
<td align="left">Spearman</td>
<td align="left">&lt; 0.001</td>
<td align="left">rho = -0.041</td>
<td align="left">Significativo, sin relevancia</td>
</tr>
<tr class="even">
<td align="left">Insurance Duration</td>
<td align="left">Spearman</td>
<td align="left">0.938</td>
<td align="left">rho ~ 0</td>
<td align="left">No significativo</td>
</tr>
<tr class="odd">
<td align="left">Number of Dependents</td>
<td align="left">Spearman</td>
<td align="left">0.670</td>
<td align="left">rho ~ 0</td>
<td align="left">No significativo</td>
</tr>
</tbody>
</table>
<p>De las 18 variables predictoras, 7 resultaron estadísticamente significativas, pero en todas los tamaños de efecto fueron prácticamente nulos (|ρ| máximo de 0.06, en Annual Income). Este patrón confirma lo anticipado en el Objetivo: con 1,200,000 observaciones, hasta las asociaciones más débiles alcanzan significancia estadística, por lo que el p-valor solo no basta como criterio de decisión. Las 3 relaciones adicionales entre predictores tampoco fueron significativas, descartando redundancias relevantes entre ellos.</p>
<p>En conjunto, esto sugiere que ninguna característica individual del cliente —ni siquiera factores intuitivamente relevantes como fumar o el tipo de póliza— explica el monto de la prima en este dataset, lo cual podría deberse a que la relación real sea conjunta o no lineal, no capturable con pruebas univariadas. Como limitación, no se ajustó por comparaciones múltiples en las 21 pruebas, aunque esto no afecta la conclusión principal al basarse en el tamaño del efecto y no solo en el p-valor. Como trabajo futuro, se recomienda ajustar un modelo de regresión múltiple que incorpore todos los predictores simultáneamente, para evaluar si en conjunto logran explicar una proporción relevante de la variabilidad de Premium Amount.</p>


</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="intro.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/2939913901/01-intro/edit/main/01-intro.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

</body>

</html>
